# https://docs.codecov.com/docs/codecovyml-reference
# validation command:
# curl -X POST --data-binary @.codecov.yaml https://codecov.io/validate
ignore:
  - "**/zz_generated*.go"
  - "cmd/build"
  - "cmd/test-stub"
  - internal/packages/internal/packagekickstart/rukpak
  - "integration"
