linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - depguard
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
run:
  skip-files:
    - "zz_generated.deepcopy.go$"
