version: "2"
run:
  build-tags:
    - integration
linters:
  default: none
  # One can't use disable and disable-all. disable-all is preferred to avoid lint failing when golangci gets updated and linters are added.
  # at the same time but it is nice to explicitly state which linters we do not want.
  #disable:
  #  - containedctx     # Context.Context within a struct (as opposed to a func parameter) is nasty for many reasons, but actually sometimes useful.
  #  - contextcheck     # Not that useful/false positives.
  #  - cyclop           # Cyclo complexity already calculated by other linters.
  #  - depguard         # We do not restrict imports.
  #  - dogsled          # Could be nice in the future.
  #  - dupl             # Could be nice in the future.
  #  - err113           # Could be nice in the future.
  #  - exhaustive       # Not that useful/false positives.
  #  - exhaustruct      # Not that useful/false positives.
  #  - forcetypeassert  # We want a panic in situations when a type is asserted.
  #  - funcorder        # Not that useful.
  #  - funlen           # We really like long functions.
  #  - gochecknoglobals # We need globals.
  #  - gochecknoinits   # We have a lot of those.
  #  - gocognit         # Not that useful/false positives.
  #  - godox            # Not that useful/false positives.
  #  - gomoddirectives  # Not that useful/false positives.
  #  - inamedparam      # Not that useful.
  #  - interfacebloat   # We do bloaty interfaces.
  #  - ireturn          # Not that useful/false positives.
  #  - mnd              # The annoy is strong.
  #  - nakedret         # Naked return good return.
  #  - nlreturn         # Could be nice in the future.
  #  - nonamedreturns   # Named return good return.
  #  - recvcheck        # Could be nice in the future.
  #  - tagliatelle      # Reports issues that are not right for us.
  #  - testpackage      # Whitebox testing is fine too.
  #  - usetesting       # Would be nice to have.
  #  - varnamelen       # Not that useful/false positives.
  #  - wrapcheck        # Not that useful/false positives.
  #  - wsl              # Not that useful/false positives.
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    gosec:
      excludes:
        - G115
        - G204
        - G301
        - G302
        - G304
        - G306
        - G601
        - G602
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        source: ^//( ?)[+]kubebuilder
      - linters:
          - lll
        source: "^\t*//( ?)http(s?)://"
      - linters:
          - paralleltest
        path: integration\/.+\.go
      - path: internal/
        text: ((comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)|exported (.+) should have comment( \(or a comment on this block\))? or be unexported|package comment should be of the form "(.+)...|comment on exported (.+) should be of the form "(.+)..."|should have a package comment)
      - path: cmd/
        text: ((comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)|exported (.+) should have comment( \(or a comment on this block\))? or be unexported|package comment should be of the form "(.+)...|comment on exported (.+) should be of the form "(.+)..."|should have a package comment)
      - path: integration/
        text: ((comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)|exported (.+) should have comment( \(or a comment on this block\))? or be unexported|package comment should be of the form "(.+)...|comment on exported (.+) should be of the form "(.+)..."|should have a package comment)
    paths:
      - internal/packages/internal/packagekickstart/rukpak
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - package-operator.run
  exclusions:
    generated: lax
    paths:
      - internal/packages/internal/packagekickstart/rukpak
      - third_party$
      - builtin$
      - examples$
