linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exportloopref
    - forbidigo
    - gocritic
    - godot
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - ifshort
    - maintidx
    - makezero
    - misspell
    - nestif
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
