apiVersion: v1
kind: ServiceAccount
metadata:
  name: remote-phase-operator
  namespace: package-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remote-phase-operator
  namespace: package-operator-system
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remote-phase-operator
  namespace: package-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: remote-phase-operator
subjects:
  - kind: ServiceAccount
    name: remote-phase-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remote-phase-operator-cluster
rules:
- apiGroups:
    - package-operator.run
  resources:
    - objectsetphases
    - objectsetphases/status
    - clusterobjectsetphases
    - clusterobjectsetphases/status
  verbs:
    - get
    - list
    - watch
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remote-phase-operator-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: remote-phase-operator-cluster
subjects:
  - kind: ServiceAccount
    name: remote-phase-operator
    namespace: package-operator-system
