apiVersion: v1
kind: Service
metadata:
  name: package-operator-metrics
  namespace: package-operator-system
  annotations:
    package-operator.run/phase: deploy
  labels:
    app.kubernetes.io/name: package-operator
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    app.kubernetes.io/name: package-operator
