apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-operator-remote-phase-manager
  annotations:
    package-operator.run/phase: rbac
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: package-operator-remote-phase-manager
  annotations:
    package-operator.run/phase: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: package-operator-remote-phase-manager
subjects:
  - kind: ServiceAccount
    name: package-operator-remote-phase-manager
