apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    package-operator.run/phase: rbac
  name: package-operator
  namespace: package-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
