// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ClusterObjectSetPhaseSpecApplyConfiguration represents a declarative configuration of the ClusterObjectSetPhaseSpec type for use
// with apply.
//
// ClusterObjectSetPhaseSpec defines the desired state of a ClusterObjectSetPhase.
type ClusterObjectSetPhaseSpecApplyConfiguration struct {
	// Disables reconciliation of the ClusterObjectSet.
	// Only Status updates will still be propagated, but object changes will not be reconciled.
	Paused *bool `json:"paused,omitempty"`
	// Revision of the parent ObjectSet to use during object adoption.
	Revision *int64 `json:"revision,omitempty"`
	// Previous revisions of the ClusterObjectSet to adopt objects from.
	Previous []PreviousRevisionReferenceApplyConfiguration `json:"previous,omitempty"`
	// Availability Probes check objects that are part of the package.
	// All probes need to succeed for a package to be considered Available.
	// Failing probes will prevent the reconciliation of objects in later phases.
	AvailabilityProbes []ObjectSetProbeApplyConfiguration `json:"availabilityProbes,omitempty"`
	// Objects belonging to this phase.
	Objects []ObjectSetObjectApplyConfiguration `json:"objects,omitempty"`
}

// ClusterObjectSetPhaseSpecApplyConfiguration constructs a declarative configuration of the ClusterObjectSetPhaseSpec type for use with
// apply.
func ClusterObjectSetPhaseSpec() *ClusterObjectSetPhaseSpecApplyConfiguration {
	return &ClusterObjectSetPhaseSpecApplyConfiguration{}
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *ClusterObjectSetPhaseSpecApplyConfiguration) WithPaused(value bool) *ClusterObjectSetPhaseSpecApplyConfiguration {
	b.Paused = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ClusterObjectSetPhaseSpecApplyConfiguration) WithRevision(value int64) *ClusterObjectSetPhaseSpecApplyConfiguration {
	b.Revision = &value
	return b
}

// WithPrevious adds the given value to the Previous field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Previous field.
func (b *ClusterObjectSetPhaseSpecApplyConfiguration) WithPrevious(values ...*PreviousRevisionReferenceApplyConfiguration) *ClusterObjectSetPhaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPrevious")
		}
		b.Previous = append(b.Previous, *values[i])
	}
	return b
}

// WithAvailabilityProbes adds the given value to the AvailabilityProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailabilityProbes field.
func (b *ClusterObjectSetPhaseSpecApplyConfiguration) WithAvailabilityProbes(values ...*ObjectSetProbeApplyConfiguration) *ClusterObjectSetPhaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAvailabilityProbes")
		}
		b.AvailabilityProbes = append(b.AvailabilityProbes, *values[i])
	}
	return b
}

// WithObjects adds the given value to the Objects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Objects field.
func (b *ClusterObjectSetPhaseSpecApplyConfiguration) WithObjects(values ...*ObjectSetObjectApplyConfiguration) *ClusterObjectSetPhaseSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObjects")
		}
		b.Objects = append(b.Objects, *values[i])
	}
	return b
}
