// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectDeploymentStatusApplyConfiguration represents a declarative configuration of the ClusterObjectDeploymentStatus type for use
// with apply.
//
// ClusterObjectDeploymentStatus defines the observed state of a ClusterObjectDeployment.
type ClusterObjectDeploymentStatusApplyConfiguration struct {
	// Conditions is a list of status conditions ths object is in.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Count of hash collisions of the ClusterObjectDeployment.
	CollisionCount *int32 `json:"collisionCount,omitempty"`
	// Computed TemplateHash.
	TemplateHash *string `json:"templateHash,omitempty"`
	// Deployment revision.
	Revision *int64 `json:"revision,omitempty"`
	// ControllerOf references the owned ClusterObjectSet revisions.
	ControllerOf []ControlledObjectReferenceApplyConfiguration `json:"controllerOf,omitempty"`
}

// ClusterObjectDeploymentStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectDeploymentStatus type for use with
// apply.
func ClusterObjectDeploymentStatus() *ClusterObjectDeploymentStatusApplyConfiguration {
	return &ClusterObjectDeploymentStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterObjectDeploymentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithCollisionCount sets the CollisionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionCount field is set to the value of the last call.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithCollisionCount(value int32) *ClusterObjectDeploymentStatusApplyConfiguration {
	b.CollisionCount = &value
	return b
}

// WithTemplateHash sets the TemplateHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateHash field is set to the value of the last call.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithTemplateHash(value string) *ClusterObjectDeploymentStatusApplyConfiguration {
	b.TemplateHash = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithRevision(value int64) *ClusterObjectDeploymentStatusApplyConfiguration {
	b.Revision = &value
	return b
}

// WithControllerOf adds the given value to the ControllerOf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ControllerOf field.
func (b *ClusterObjectDeploymentStatusApplyConfiguration) WithControllerOf(values ...*ControlledObjectReferenceApplyConfiguration) *ClusterObjectDeploymentStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithControllerOf")
		}
		b.ControllerOf = append(b.ControllerOf, *values[i])
	}
	return b
}
