// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectDeploymentSpecApplyConfiguration represents a declarative configuration of the ClusterObjectDeploymentSpec type for use
// with apply.
//
// ClusterObjectDeploymentSpec defines the desired state of a ClusterObjectDeployment.
type ClusterObjectDeploymentSpecApplyConfiguration struct {
	// Number of old revisions in the form of archived ObjectSets to keep.
	RevisionHistoryLimit *int32 `json:"revisionHistoryLimit,omitempty"`
	// Selector targets ObjectSets managed by this Deployment.
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	// Template to create new ObjectSets from.
	Template *ObjectSetTemplateApplyConfiguration `json:"template,omitempty"`
	// If Paused is true, the object and its children will not be reconciled.
	Paused *bool `json:"paused,omitempty"`
}

// ClusterObjectDeploymentSpecApplyConfiguration constructs a declarative configuration of the ClusterObjectDeploymentSpec type for use with
// apply.
func ClusterObjectDeploymentSpec() *ClusterObjectDeploymentSpecApplyConfiguration {
	return &ClusterObjectDeploymentSpecApplyConfiguration{}
}

// WithRevisionHistoryLimit sets the RevisionHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionHistoryLimit field is set to the value of the last call.
func (b *ClusterObjectDeploymentSpecApplyConfiguration) WithRevisionHistoryLimit(value int32) *ClusterObjectDeploymentSpecApplyConfiguration {
	b.RevisionHistoryLimit = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *ClusterObjectDeploymentSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *ClusterObjectDeploymentSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ClusterObjectDeploymentSpecApplyConfiguration) WithTemplate(value *ObjectSetTemplateApplyConfiguration) *ClusterObjectDeploymentSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *ClusterObjectDeploymentSpecApplyConfiguration) WithPaused(value bool) *ClusterObjectDeploymentSpecApplyConfiguration {
	b.Paused = &value
	return b
}
