// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
	internal "package-operator.run/apis/applyconfigurations/internal"
	corev1alpha1 "package-operator.run/apis/core/v1alpha1"
)

// ClusterObjectSetPhaseApplyConfiguration represents a declarative configuration of the ClusterObjectSetPhase type for use
// with apply.
//
// ClusterObjectSetPhase is an internal API, allowing a ClusterObjectSet to delegate a
// single phase to another custom controller. ClusterObjectSets will create subordinate
// ClusterObjectSetPhases when `.class` is set within the phase specification.
type ClusterObjectSetPhaseApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *ClusterObjectSetPhaseSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *ClusterObjectSetPhaseStatusApplyConfiguration `json:"status,omitempty"`
}

// ClusterObjectSetPhase constructs a declarative configuration of the ClusterObjectSetPhase type for use with
// apply.
func ClusterObjectSetPhase(name string) *ClusterObjectSetPhaseApplyConfiguration {
	b := &ClusterObjectSetPhaseApplyConfiguration{}
	b.WithName(name)
	b.WithKind("ClusterObjectSetPhase")
	b.WithAPIVersion("package-operator.run/v1alpha1")
	return b
}

// ExtractClusterObjectSetPhaseFrom extracts the applied configuration owned by fieldManager from
// clusterObjectSetPhase for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// clusterObjectSetPhase must be a unmodified ClusterObjectSetPhase API object that was retrieved from the Kubernetes API.
// ExtractClusterObjectSetPhaseFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractClusterObjectSetPhaseFrom(clusterObjectSetPhase *corev1alpha1.ClusterObjectSetPhase, fieldManager string, subresource string) (*ClusterObjectSetPhaseApplyConfiguration, error) {
	b := &ClusterObjectSetPhaseApplyConfiguration{}
	err := managedfields.ExtractInto(clusterObjectSetPhase, internal.Parser().Type("run.package-operator.apis.core.v1alpha1.ClusterObjectSetPhase"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(clusterObjectSetPhase.Name)

	b.WithKind("ClusterObjectSetPhase")
	b.WithAPIVersion("package-operator.run/v1alpha1")
	return b, nil
}

// ExtractClusterObjectSetPhase extracts the applied configuration owned by fieldManager from
// clusterObjectSetPhase. If no managedFields are found in clusterObjectSetPhase for fieldManager, a
// ClusterObjectSetPhaseApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// clusterObjectSetPhase must be a unmodified ClusterObjectSetPhase API object that was retrieved from the Kubernetes API.
// ExtractClusterObjectSetPhase provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractClusterObjectSetPhase(clusterObjectSetPhase *corev1alpha1.ClusterObjectSetPhase, fieldManager string) (*ClusterObjectSetPhaseApplyConfiguration, error) {
	return ExtractClusterObjectSetPhaseFrom(clusterObjectSetPhase, fieldManager, "")
}

// ExtractClusterObjectSetPhaseStatus extracts the applied configuration owned by fieldManager from
// clusterObjectSetPhase for the status subresource.
func ExtractClusterObjectSetPhaseStatus(clusterObjectSetPhase *corev1alpha1.ClusterObjectSetPhase, fieldManager string) (*ClusterObjectSetPhaseApplyConfiguration, error) {
	return ExtractClusterObjectSetPhaseFrom(clusterObjectSetPhase, fieldManager, "status")
}

func (b ClusterObjectSetPhaseApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithKind(value string) *ClusterObjectSetPhaseApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithAPIVersion(value string) *ClusterObjectSetPhaseApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithName(value string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithGenerateName(value string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithNamespace(value string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithUID(value types.UID) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithResourceVersion(value string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithGeneration(value int64) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithCreationTimestamp(value metav1.Time) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithLabels(entries map[string]string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithAnnotations(entries map[string]string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithFinalizers(values ...string) *ClusterObjectSetPhaseApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ClusterObjectSetPhaseApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithSpec(value *ClusterObjectSetPhaseSpecApplyConfiguration) *ClusterObjectSetPhaseApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ClusterObjectSetPhaseApplyConfiguration) WithStatus(value *ClusterObjectSetPhaseStatusApplyConfiguration) *ClusterObjectSetPhaseApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *ClusterObjectSetPhaseApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *ClusterObjectSetPhaseApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ClusterObjectSetPhaseApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *ClusterObjectSetPhaseApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
