// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterObjectSetPhaseStatusApplyConfiguration represents a declarative configuration of the ClusterObjectSetPhaseStatus type for use
// with apply.
//
// ClusterObjectSetPhaseStatus defines the observed state of a ClusterObjectSetPhase.
type ClusterObjectSetPhaseStatusApplyConfiguration struct {
	// Conditions is a list of status conditions ths object is in.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// References all objects controlled by this instance.
	ControllerOf []ControlledObjectReferenceApplyConfiguration `json:"controllerOf,omitempty"`
}

// ClusterObjectSetPhaseStatusApplyConfiguration constructs a declarative configuration of the ClusterObjectSetPhaseStatus type for use with
// apply.
func ClusterObjectSetPhaseStatus() *ClusterObjectSetPhaseStatusApplyConfiguration {
	return &ClusterObjectSetPhaseStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterObjectSetPhaseStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterObjectSetPhaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithControllerOf adds the given value to the ControllerOf field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ControllerOf field.
func (b *ClusterObjectSetPhaseStatusApplyConfiguration) WithControllerOf(values ...*ControlledObjectReferenceApplyConfiguration) *ClusterObjectSetPhaseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithControllerOf")
		}
		b.ControllerOf = append(b.ControllerOf, *values[i])
	}
	return b
}
