// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ControlledObjectReferenceApplyConfiguration represents a declarative configuration of the ControlledObjectReference type for use
// with apply.
//
// ControlledObjectReference an object controlled by this object.
type ControlledObjectReferenceApplyConfiguration struct {
	// Object Kind.
	Kind *string `json:"kind,omitempty"`
	// Object Group.
	Group *string `json:"group,omitempty"`
	// Object Name.
	Name *string `json:"name,omitempty"`
	// Object Namespace.
	Namespace *string `json:"namespace,omitempty"`
	// Object Version.
	Version *string `json:"version,omitempty"`
}

// ControlledObjectReferenceApplyConfiguration constructs a declarative configuration of the ControlledObjectReference type for use with
// apply.
func ControlledObjectReference() *ControlledObjectReferenceApplyConfiguration {
	return &ControlledObjectReferenceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ControlledObjectReferenceApplyConfiguration) WithKind(value string) *ControlledObjectReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *ControlledObjectReferenceApplyConfiguration) WithGroup(value string) *ControlledObjectReferenceApplyConfiguration {
	b.Group = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ControlledObjectReferenceApplyConfiguration) WithName(value string) *ControlledObjectReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ControlledObjectReferenceApplyConfiguration) WithNamespace(value string) *ControlledObjectReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *ControlledObjectReferenceApplyConfiguration) WithVersion(value string) *ControlledObjectReferenceApplyConfiguration {
	b.Version = &value
	return b
}
