// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostedClusterPackageStrategyRollingUpgradeApplyConfiguration represents a declarative configuration of the HostedClusterPackageStrategyRollingUpgrade type for use
// with apply.
//
// HostedClusterPackageStrategyRollingUpgrade describes the
// rolling upgrade strategy for HostedClusterPackages.
type HostedClusterPackageStrategyRollingUpgradeApplyConfiguration struct {
	// MaxUnavailable defines how many Packages may become unavailable during upgrade at the same time.
	// Cannot be below 1, because we cannot surge to create more instances.
	MaxUnavailable *int `json:"maxUnavailable,omitempty"`
}

// HostedClusterPackageStrategyRollingUpgradeApplyConfiguration constructs a declarative configuration of the HostedClusterPackageStrategyRollingUpgrade type for use with
// apply.
func HostedClusterPackageStrategyRollingUpgrade() *HostedClusterPackageStrategyRollingUpgradeApplyConfiguration {
	return &HostedClusterPackageStrategyRollingUpgradeApplyConfiguration{}
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *HostedClusterPackageStrategyRollingUpgradeApplyConfiguration) WithMaxUnavailable(value int) *HostedClusterPackageStrategyRollingUpgradeApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}
