// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostedClusterPackagePartitionSpecApplyConfiguration represents a declarative configuration of the HostedClusterPackagePartitionSpec type for use
// with apply.
//
// HostedClusterPackagePartitionSpec describes settings to partition HostedClusters into groups for upgrades.
// Partitions will be upgraded after each other:
// Upgrades in the next partition will only start after the previous has finished.
// HostedClusters without the label will be put into an implicit "unknown" group
// and will get upgraded LAST.
type HostedClusterPackagePartitionSpecApplyConfiguration struct {
	// LabelKey defines a labelKey to group objects on.
	LabelKey *string `json:"labelKey,omitempty"`
	// Controls how partitions are ordered.
	// By default items will be sorted AlphaNumeric ascending.
	Order *HostedClusterPackagePartitionOrderSpecApplyConfiguration `json:"order,omitempty"`
}

// HostedClusterPackagePartitionSpecApplyConfiguration constructs a declarative configuration of the HostedClusterPackagePartitionSpec type for use with
// apply.
func HostedClusterPackagePartitionSpec() *HostedClusterPackagePartitionSpecApplyConfiguration {
	return &HostedClusterPackagePartitionSpecApplyConfiguration{}
}

// WithLabelKey sets the LabelKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelKey field is set to the value of the last call.
func (b *HostedClusterPackagePartitionSpecApplyConfiguration) WithLabelKey(value string) *HostedClusterPackagePartitionSpecApplyConfiguration {
	b.LabelKey = &value
	return b
}

// WithOrder sets the Order field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Order field is set to the value of the last call.
func (b *HostedClusterPackagePartitionSpecApplyConfiguration) WithOrder(value *HostedClusterPackagePartitionOrderSpecApplyConfiguration) *HostedClusterPackagePartitionSpecApplyConfiguration {
	b.Order = value
	return b
}
