// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "package-operator.run/apis/core/v1alpha1"
)

// HostedClusterPackageStrategyApplyConfiguration represents a declarative configuration of the HostedClusterPackageStrategy type for use
// with apply.
//
// HostedClusterPackageStrategy describes the rollout strategy for a HostedClusterPackage.
type HostedClusterPackageStrategyApplyConfiguration struct {
	// Updates all matching Packages instantly.
	Instant *corev1alpha1.HostedClusterPackageStrategyInstant `json:"instant,omitempty"`
	// Performs a rolling upgrade according to maxUnavailable.
	RollingUpgrade *HostedClusterPackageStrategyRollingUpgradeApplyConfiguration `json:"rollingUpgrade,omitempty"`
}

// HostedClusterPackageStrategyApplyConfiguration constructs a declarative configuration of the HostedClusterPackageStrategy type for use with
// apply.
func HostedClusterPackageStrategy() *HostedClusterPackageStrategyApplyConfiguration {
	return &HostedClusterPackageStrategyApplyConfiguration{}
}

// WithInstant sets the Instant field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Instant field is set to the value of the last call.
func (b *HostedClusterPackageStrategyApplyConfiguration) WithInstant(value corev1alpha1.HostedClusterPackageStrategyInstant) *HostedClusterPackageStrategyApplyConfiguration {
	b.Instant = &value
	return b
}

// WithRollingUpgrade sets the RollingUpgrade field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RollingUpgrade field is set to the value of the last call.
func (b *HostedClusterPackageStrategyApplyConfiguration) WithRollingUpgrade(value *HostedClusterPackageStrategyRollingUpgradeApplyConfiguration) *HostedClusterPackageStrategyApplyConfiguration {
	b.RollingUpgrade = value
	return b
}
