// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HostedClusterPackageSpecApplyConfiguration represents a declarative configuration of the HostedClusterPackageSpec type for use
// with apply.
//
// HostedClusterPackageSpec is the description of a HostedClusterPackage.
type HostedClusterPackageSpecApplyConfiguration struct {
	Strategy *HostedClusterPackageStrategyApplyConfiguration `json:"strategy,omitempty"`
	// HostedClusterSelector is a label query matching HostedClusters that the Package should be rolled out to.
	HostedClusterSelector *v1.LabelSelectorApplyConfiguration `json:"hostedClusterSelector,omitempty"`
	// Template describes the Package that should be created when new
	// HostedClusters matching the hostedClusterSelector are detected.
	Template *PackageTemplateSpecApplyConfiguration `json:"template,omitempty"`
	// Partition HostedClusters by label value.
	// All packages in the same partition will have to be upgraded
	// before progressing to the next partition.
	Partition *HostedClusterPackagePartitionSpecApplyConfiguration `json:"partition,omitempty"`
}

// HostedClusterPackageSpecApplyConfiguration constructs a declarative configuration of the HostedClusterPackageSpec type for use with
// apply.
func HostedClusterPackageSpec() *HostedClusterPackageSpecApplyConfiguration {
	return &HostedClusterPackageSpecApplyConfiguration{}
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *HostedClusterPackageSpecApplyConfiguration) WithStrategy(value *HostedClusterPackageStrategyApplyConfiguration) *HostedClusterPackageSpecApplyConfiguration {
	b.Strategy = value
	return b
}

// WithHostedClusterSelector sets the HostedClusterSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostedClusterSelector field is set to the value of the last call.
func (b *HostedClusterPackageSpecApplyConfiguration) WithHostedClusterSelector(value *v1.LabelSelectorApplyConfiguration) *HostedClusterPackageSpecApplyConfiguration {
	b.HostedClusterSelector = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *HostedClusterPackageSpecApplyConfiguration) WithTemplate(value *PackageTemplateSpecApplyConfiguration) *HostedClusterPackageSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithPartition sets the Partition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Partition field is set to the value of the last call.
func (b *HostedClusterPackageSpecApplyConfiguration) WithPartition(value *HostedClusterPackagePartitionSpecApplyConfiguration) *HostedClusterPackageSpecApplyConfiguration {
	b.Partition = value
	return b
}
