// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// HostedClusterPackagePartitionStatusApplyConfiguration represents a declarative configuration of the HostedClusterPackagePartitionStatus type for use
// with apply.
//
// HostedClusterPackagePartitionStatus describes the status of a partition.
type HostedClusterPackagePartitionStatusApplyConfiguration struct {
	// Name of the partition.
	Name                                               *string `json:"name,omitempty"`
	HostedClusterPackageCountsStatusApplyConfiguration `json:",inline"`
}

// HostedClusterPackagePartitionStatusApplyConfiguration constructs a declarative configuration of the HostedClusterPackagePartitionStatus type for use with
// apply.
func HostedClusterPackagePartitionStatus() *HostedClusterPackagePartitionStatusApplyConfiguration {
	return &HostedClusterPackagePartitionStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HostedClusterPackagePartitionStatusApplyConfiguration) WithName(value string) *HostedClusterPackagePartitionStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *HostedClusterPackagePartitionStatusApplyConfiguration) WithObservedGeneration(value int32) *HostedClusterPackagePartitionStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithAvailablePackages sets the AvailablePackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailablePackages field is set to the value of the last call.
func (b *HostedClusterPackagePartitionStatusApplyConfiguration) WithAvailablePackages(value int32) *HostedClusterPackagePartitionStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.AvailablePackages = &value
	return b
}

// WithProgressedPackages sets the ProgressedPackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressedPackages field is set to the value of the last call.
func (b *HostedClusterPackagePartitionStatusApplyConfiguration) WithProgressedPackages(value int32) *HostedClusterPackagePartitionStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.ProgressedPackages = &value
	return b
}

// WithUpdatedPackages sets the UpdatedPackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedPackages field is set to the value of the last call.
func (b *HostedClusterPackagePartitionStatusApplyConfiguration) WithUpdatedPackages(value int32) *HostedClusterPackagePartitionStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.UpdatedPackages = &value
	return b
}

// WithTotalPackages sets the TotalPackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalPackages field is set to the value of the last call.
func (b *HostedClusterPackagePartitionStatusApplyConfiguration) WithTotalPackages(value int32) *HostedClusterPackagePartitionStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.TotalPackages = &value
	return b
}
