// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// HostedClusterPackageRefStatusApplyConfiguration represents a declarative configuration of the HostedClusterPackageRefStatus type for use
// with apply.
//
// HostedClusterPackageRefStatus holds a reference to upgrades in-flight.
type HostedClusterPackageRefStatusApplyConfiguration struct {
	UID       *types.UID `json:"uid,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Namespace *string    `json:"namespace,omitempty"`
}

// HostedClusterPackageRefStatusApplyConfiguration constructs a declarative configuration of the HostedClusterPackageRefStatus type for use with
// apply.
func HostedClusterPackageRefStatus() *HostedClusterPackageRefStatusApplyConfiguration {
	return &HostedClusterPackageRefStatusApplyConfiguration{}
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *HostedClusterPackageRefStatusApplyConfiguration) WithUID(value types.UID) *HostedClusterPackageRefStatusApplyConfiguration {
	b.UID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HostedClusterPackageRefStatusApplyConfiguration) WithName(value string) *HostedClusterPackageRefStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *HostedClusterPackageRefStatusApplyConfiguration) WithNamespace(value string) *HostedClusterPackageRefStatusApplyConfiguration {
	b.Namespace = &value
	return b
}
