// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// HostedClusterPackageStatusApplyConfiguration represents a declarative configuration of the HostedClusterPackageStatus type for use
// with apply.
//
// HostedClusterPackageStatus describes the status of a HostedClusterPackage.
type HostedClusterPackageStatusApplyConfiguration struct {
	// Conditions is a list of status conditions this object is in.
	Conditions                                         []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	HostedClusterPackageCountsStatusApplyConfiguration `json:",inline"`
	// Count of packages found by partition.
	Partitions []HostedClusterPackagePartitionStatusApplyConfiguration `json:"partitions,omitempty"`
	// Processing set of packages during upgrade.
	Processing []HostedClusterPackageRefStatusApplyConfiguration `json:"processing,omitempty"`
}

// HostedClusterPackageStatusApplyConfiguration constructs a declarative configuration of the HostedClusterPackageStatus type for use with
// apply.
func HostedClusterPackageStatus() *HostedClusterPackageStatusApplyConfiguration {
	return &HostedClusterPackageStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *HostedClusterPackageStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *HostedClusterPackageStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *HostedClusterPackageStatusApplyConfiguration) WithObservedGeneration(value int32) *HostedClusterPackageStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.ObservedGeneration = &value
	return b
}

// WithAvailablePackages sets the AvailablePackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailablePackages field is set to the value of the last call.
func (b *HostedClusterPackageStatusApplyConfiguration) WithAvailablePackages(value int32) *HostedClusterPackageStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.AvailablePackages = &value
	return b
}

// WithProgressedPackages sets the ProgressedPackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProgressedPackages field is set to the value of the last call.
func (b *HostedClusterPackageStatusApplyConfiguration) WithProgressedPackages(value int32) *HostedClusterPackageStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.ProgressedPackages = &value
	return b
}

// WithUpdatedPackages sets the UpdatedPackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedPackages field is set to the value of the last call.
func (b *HostedClusterPackageStatusApplyConfiguration) WithUpdatedPackages(value int32) *HostedClusterPackageStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.UpdatedPackages = &value
	return b
}

// WithTotalPackages sets the TotalPackages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalPackages field is set to the value of the last call.
func (b *HostedClusterPackageStatusApplyConfiguration) WithTotalPackages(value int32) *HostedClusterPackageStatusApplyConfiguration {
	b.HostedClusterPackageCountsStatusApplyConfiguration.TotalPackages = &value
	return b
}

// WithPartitions adds the given value to the Partitions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Partitions field.
func (b *HostedClusterPackageStatusApplyConfiguration) WithPartitions(values ...*HostedClusterPackagePartitionStatusApplyConfiguration) *HostedClusterPackageStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPartitions")
		}
		b.Partitions = append(b.Partitions, *values[i])
	}
	return b
}

// WithProcessing adds the given value to the Processing field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Processing field.
func (b *HostedClusterPackageStatusApplyConfiguration) WithProcessing(values ...*HostedClusterPackageRefStatusApplyConfiguration) *HostedClusterPackageStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProcessing")
		}
		b.Processing = append(b.Processing, *values[i])
	}
	return b
}
