// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ObjectTemplateStatusApplyConfiguration represents a declarative configuration of the ObjectTemplateStatus type for use
// with apply.
//
// ObjectTemplateStatus defines the observed state of a ObjectTemplate ie the status of the templated object.
type ObjectTemplateStatusApplyConfiguration struct {
	// Conditions is a list of status conditions the templated object is in.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ControllerOf references the templated object.
	ControllerOf *ControlledObjectReferenceApplyConfiguration `json:"controllerOf,omitempty"`
}

// ObjectTemplateStatusApplyConfiguration constructs a declarative configuration of the ObjectTemplateStatus type for use with
// apply.
func ObjectTemplateStatus() *ObjectTemplateStatusApplyConfiguration {
	return &ObjectTemplateStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ObjectTemplateStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ObjectTemplateStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithControllerOf sets the ControllerOf field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControllerOf field is set to the value of the last call.
func (b *ObjectTemplateStatusApplyConfiguration) WithControllerOf(value *ControlledObjectReferenceApplyConfiguration) *ObjectTemplateStatusApplyConfiguration {
	b.ControllerOf = value
	return b
}
