// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectTemplateSourceItemApplyConfiguration represents a declarative configuration of the ObjectTemplateSourceItem type for use
// with apply.
//
// ObjectTemplateSourceItem defines a source item for an object template.
type ObjectTemplateSourceItemApplyConfiguration struct {
	// JSONPath to value in source object.
	Key *string `json:"key,omitempty"`
	// JSONPath to destination in which to store copy of the source value.
	Destination *string `json:"destination,omitempty"`
}

// ObjectTemplateSourceItemApplyConfiguration constructs a declarative configuration of the ObjectTemplateSourceItem type for use with
// apply.
func ObjectTemplateSourceItem() *ObjectTemplateSourceItemApplyConfiguration {
	return &ObjectTemplateSourceItemApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ObjectTemplateSourceItemApplyConfiguration) WithKey(value string) *ObjectTemplateSourceItemApplyConfiguration {
	b.Key = &value
	return b
}

// WithDestination sets the Destination field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Destination field is set to the value of the last call.
func (b *ObjectTemplateSourceItemApplyConfiguration) WithDestination(value string) *ObjectTemplateSourceItemApplyConfiguration {
	b.Destination = &value
	return b
}
