// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	corev1alpha1 "package-operator.run/apis/core/v1alpha1"
)

// ObjectSetObjectApplyConfiguration represents a declarative configuration of the ObjectSetObject type for use
// with apply.
//
// ObjectSetObject is an object that is part of the phase of an ObjectSet.
type ObjectSetObjectApplyConfiguration struct {
	Object *unstructured.Unstructured `json:"object,omitempty"`
	// Collision protection prevents Package Operator from working on objects already under
	// management by a different operator.
	CollisionProtection *corev1alpha1.CollisionProtection `json:"collisionProtection,omitempty"`
	// Maps conditions from this object into the Package Operator APIs.
	ConditionMappings []ConditionMappingApplyConfiguration `json:"conditionMappings,omitempty"`
}

// ObjectSetObjectApplyConfiguration constructs a declarative configuration of the ObjectSetObject type for use with
// apply.
func ObjectSetObject() *ObjectSetObjectApplyConfiguration {
	return &ObjectSetObjectApplyConfiguration{}
}

// WithObject sets the Object field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Object field is set to the value of the last call.
func (b *ObjectSetObjectApplyConfiguration) WithObject(value unstructured.Unstructured) *ObjectSetObjectApplyConfiguration {
	b.Object = &value
	return b
}

// WithCollisionProtection sets the CollisionProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionProtection field is set to the value of the last call.
func (b *ObjectSetObjectApplyConfiguration) WithCollisionProtection(value corev1alpha1.CollisionProtection) *ObjectSetObjectApplyConfiguration {
	b.CollisionProtection = &value
	return b
}

// WithConditionMappings adds the given value to the ConditionMappings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ConditionMappings field.
func (b *ObjectSetObjectApplyConfiguration) WithConditionMappings(values ...*ConditionMappingApplyConfiguration) *ObjectSetObjectApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditionMappings")
		}
		b.ConditionMappings = append(b.ConditionMappings, *values[i])
	}
	return b
}
