// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "package-operator.run/apis/core/v1alpha1"
)

// ObjectSetSpecApplyConfiguration represents a declarative configuration of the ObjectSetSpec type for use
// with apply.
//
// ObjectSetSpec defines the desired state of a ObjectSet.
type ObjectSetSpecApplyConfiguration struct {
	// Specifies the lifecycle state of the ObjectSet.
	LifecycleState *corev1alpha1.ObjectSetLifecycleState `json:"lifecycleState,omitempty"`
	// Previous revisions of the ObjectSet to adopt objects from.
	Previous                                []PreviousRevisionReferenceApplyConfiguration `json:"previous,omitempty"`
	ObjectSetTemplateSpecApplyConfiguration `json:",inline"`
	// Computed revision number, monotonically increasing.
	Revision *int64 `json:"revision,omitempty"`
}

// ObjectSetSpecApplyConfiguration constructs a declarative configuration of the ObjectSetSpec type for use with
// apply.
func ObjectSetSpec() *ObjectSetSpecApplyConfiguration {
	return &ObjectSetSpecApplyConfiguration{}
}

// WithLifecycleState sets the LifecycleState field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleState field is set to the value of the last call.
func (b *ObjectSetSpecApplyConfiguration) WithLifecycleState(value corev1alpha1.ObjectSetLifecycleState) *ObjectSetSpecApplyConfiguration {
	b.LifecycleState = &value
	return b
}

// WithPrevious adds the given value to the Previous field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Previous field.
func (b *ObjectSetSpecApplyConfiguration) WithPrevious(values ...*PreviousRevisionReferenceApplyConfiguration) *ObjectSetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPrevious")
		}
		b.Previous = append(b.Previous, *values[i])
	}
	return b
}

// WithPhases adds the given value to the Phases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Phases field.
func (b *ObjectSetSpecApplyConfiguration) WithPhases(values ...*ObjectSetTemplatePhaseApplyConfiguration) *ObjectSetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhases")
		}
		b.ObjectSetTemplateSpecApplyConfiguration.Phases = append(b.ObjectSetTemplateSpecApplyConfiguration.Phases, *values[i])
	}
	return b
}

// WithAvailabilityProbes adds the given value to the AvailabilityProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailabilityProbes field.
func (b *ObjectSetSpecApplyConfiguration) WithAvailabilityProbes(values ...*ObjectSetProbeApplyConfiguration) *ObjectSetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAvailabilityProbes")
		}
		b.ObjectSetTemplateSpecApplyConfiguration.AvailabilityProbes = append(b.ObjectSetTemplateSpecApplyConfiguration.AvailabilityProbes, *values[i])
	}
	return b
}

// WithSuccessDelaySeconds sets the SuccessDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessDelaySeconds field is set to the value of the last call.
func (b *ObjectSetSpecApplyConfiguration) WithSuccessDelaySeconds(value int32) *ObjectSetSpecApplyConfiguration {
	b.ObjectSetTemplateSpecApplyConfiguration.SuccessDelaySeconds = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ObjectSetSpecApplyConfiguration) WithRevision(value int64) *ObjectSetSpecApplyConfiguration {
	b.Revision = &value
	return b
}
