// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectSetTemplatePhaseApplyConfiguration represents a declarative configuration of the ObjectSetTemplatePhase type for use
// with apply.
//
// ObjectSetTemplatePhase configures the reconcile phase of ObjectSets.
type ObjectSetTemplatePhaseApplyConfiguration struct {
	// Name of the reconcile phase. Must be unique within a ObjectSet.
	Name *string `json:"name,omitempty"`
	// If non empty, the ObjectSet controller will delegate phase reconciliation
	// to another controller, by creating an ObjectSetPhase object. If set to the
	// string "default" the built-in Package Operator ObjectSetPhase controller
	// will reconcile the object in the same way the ObjectSet would. If set to
	// any other string, an out-of-tree controller needs to be present to handle
	// ObjectSetPhase objects.
	Class *string `json:"class,omitempty"`
	// Objects belonging to this phase.
	Objects []ObjectSetObjectApplyConfiguration `json:"objects,omitempty"`
	// References to ObjectSlices containing objects for this phase.
	Slices []string `json:"slices,omitempty"`
}

// ObjectSetTemplatePhaseApplyConfiguration constructs a declarative configuration of the ObjectSetTemplatePhase type for use with
// apply.
func ObjectSetTemplatePhase() *ObjectSetTemplatePhaseApplyConfiguration {
	return &ObjectSetTemplatePhaseApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObjectSetTemplatePhaseApplyConfiguration) WithName(value string) *ObjectSetTemplatePhaseApplyConfiguration {
	b.Name = &value
	return b
}

// WithClass sets the Class field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Class field is set to the value of the last call.
func (b *ObjectSetTemplatePhaseApplyConfiguration) WithClass(value string) *ObjectSetTemplatePhaseApplyConfiguration {
	b.Class = &value
	return b
}

// WithObjects adds the given value to the Objects field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Objects field.
func (b *ObjectSetTemplatePhaseApplyConfiguration) WithObjects(values ...*ObjectSetObjectApplyConfiguration) *ObjectSetTemplatePhaseApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithObjects")
		}
		b.Objects = append(b.Objects, *values[i])
	}
	return b
}

// WithSlices adds the given value to the Slices field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Slices field.
func (b *ObjectSetTemplatePhaseApplyConfiguration) WithSlices(values ...string) *ObjectSetTemplatePhaseApplyConfiguration {
	for i := range values {
		b.Slices = append(b.Slices, values[i])
	}
	return b
}
