// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectTemplateSourceApplyConfiguration represents a declarative configuration of the ObjectTemplateSource type for use
// with apply.
//
// ObjectTemplateSource defines a source for a template.
type ObjectTemplateSourceApplyConfiguration struct {
	APIVersion *string                                      `json:"apiVersion,omitempty"`
	Kind       *string                                      `json:"kind,omitempty"`
	Namespace  *string                                      `json:"namespace,omitempty"`
	Name       *string                                      `json:"name,omitempty"`
	Items      []ObjectTemplateSourceItemApplyConfiguration `json:"items,omitempty"`
	// Marks this source as optional.
	// The templated object will still be applied if optional sources are not found.
	// If the source object is created later on, it will be eventually picked up.
	Optional *bool `json:"optional,omitempty"`
}

// ObjectTemplateSourceApplyConfiguration constructs a declarative configuration of the ObjectTemplateSource type for use with
// apply.
func ObjectTemplateSource() *ObjectTemplateSourceApplyConfiguration {
	return &ObjectTemplateSourceApplyConfiguration{}
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ObjectTemplateSourceApplyConfiguration) WithAPIVersion(value string) *ObjectTemplateSourceApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ObjectTemplateSourceApplyConfiguration) WithKind(value string) *ObjectTemplateSourceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ObjectTemplateSourceApplyConfiguration) WithNamespace(value string) *ObjectTemplateSourceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ObjectTemplateSourceApplyConfiguration) WithName(value string) *ObjectTemplateSourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithItems adds the given value to the Items field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Items field.
func (b *ObjectTemplateSourceApplyConfiguration) WithItems(values ...*ObjectTemplateSourceItemApplyConfiguration) *ObjectTemplateSourceApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithItems")
		}
		b.Items = append(b.Items, *values[i])
	}
	return b
}

// WithOptional sets the Optional field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Optional field is set to the value of the last call.
func (b *ObjectTemplateSourceApplyConfiguration) WithOptional(value bool) *ObjectTemplateSourceApplyConfiguration {
	b.Optional = &value
	return b
}
