// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectSetProbeApplyConfiguration represents a declarative configuration of the ObjectSetProbe type for use
// with apply.
//
// ObjectSetProbe define how ObjectSets check their children for their status.
type ObjectSetProbeApplyConfiguration struct {
	// Probe configuration parameters.
	Probes []ProbeApplyConfiguration `json:"probes,omitempty"`
	// Selector specifies which objects this probe should target.
	Selector *ProbeSelectorApplyConfiguration `json:"selector,omitempty"`
}

// ObjectSetProbeApplyConfiguration constructs a declarative configuration of the ObjectSetProbe type for use with
// apply.
func ObjectSetProbe() *ObjectSetProbeApplyConfiguration {
	return &ObjectSetProbeApplyConfiguration{}
}

// WithProbes adds the given value to the Probes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Probes field.
func (b *ObjectSetProbeApplyConfiguration) WithProbes(values ...*ProbeApplyConfiguration) *ObjectSetProbeApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProbes")
		}
		b.Probes = append(b.Probes, *values[i])
	}
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *ObjectSetProbeApplyConfiguration) WithSelector(value *ProbeSelectorApplyConfiguration) *ObjectSetProbeApplyConfiguration {
	b.Selector = value
	return b
}
