// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ObjectDeploymentSpecApplyConfiguration represents a declarative configuration of the ObjectDeploymentSpec type for use
// with apply.
//
// ObjectDeploymentSpec defines the desired state of an ObjectDeployment.
type ObjectDeploymentSpecApplyConfiguration struct {
	// Number of old revisions in the form of archived ObjectSets to keep.
	RevisionHistoryLimit *int32 `json:"revisionHistoryLimit,omitempty"`
	// Selector targets ObjectSets managed by this Deployment.
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	// Template to create new ObjectSets from.
	Template *ObjectSetTemplateApplyConfiguration `json:"template,omitempty"`
	// If Paused is true, the object and its children will not be reconciled.
	Paused *bool `json:"paused,omitempty"`
}

// ObjectDeploymentSpecApplyConfiguration constructs a declarative configuration of the ObjectDeploymentSpec type for use with
// apply.
func ObjectDeploymentSpec() *ObjectDeploymentSpecApplyConfiguration {
	return &ObjectDeploymentSpecApplyConfiguration{}
}

// WithRevisionHistoryLimit sets the RevisionHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionHistoryLimit field is set to the value of the last call.
func (b *ObjectDeploymentSpecApplyConfiguration) WithRevisionHistoryLimit(value int32) *ObjectDeploymentSpecApplyConfiguration {
	b.RevisionHistoryLimit = &value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *ObjectDeploymentSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *ObjectDeploymentSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ObjectDeploymentSpecApplyConfiguration) WithTemplate(value *ObjectSetTemplateApplyConfiguration) *ObjectDeploymentSpecApplyConfiguration {
	b.Template = value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *ObjectDeploymentSpecApplyConfiguration) WithPaused(value bool) *ObjectDeploymentSpecApplyConfiguration {
	b.Paused = &value
	return b
}
