// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectTemplateSpecApplyConfiguration represents a declarative configuration of the ObjectTemplateSpec type for use
// with apply.
//
// ObjectTemplateSpec specification.
type ObjectTemplateSpecApplyConfiguration struct {
	// Go template of a Kubernetes manifest
	Template *string `json:"template,omitempty"`
	// Objects in which configuration parameters are fetched
	Sources []ObjectTemplateSourceApplyConfiguration `json:"sources,omitempty"`
}

// ObjectTemplateSpecApplyConfiguration constructs a declarative configuration of the ObjectTemplateSpec type for use with
// apply.
func ObjectTemplateSpec() *ObjectTemplateSpecApplyConfiguration {
	return &ObjectTemplateSpecApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ObjectTemplateSpecApplyConfiguration) WithTemplate(value string) *ObjectTemplateSpecApplyConfiguration {
	b.Template = &value
	return b
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *ObjectTemplateSpecApplyConfiguration) WithSources(values ...*ObjectTemplateSourceApplyConfiguration) *ObjectTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSources")
		}
		b.Sources = append(b.Sources, *values[i])
	}
	return b
}
