// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ObjectSetTemplateSpecApplyConfiguration represents a declarative configuration of the ObjectSetTemplateSpec type for use
// with apply.
//
// ObjectSetTemplateSpec defines an object set.
// WARNING: when modifying fields in ObjectSetTemplateSpec
// also update validation rules in (Cluster)ObjectSetSpec.
type ObjectSetTemplateSpecApplyConfiguration struct {
	// Reconcile phase configuration for a ObjectSet.
	// Phases will be reconciled in order and the contained objects checked
	// against given probes before continuing with the next phase.
	Phases []ObjectSetTemplatePhaseApplyConfiguration `json:"phases,omitempty"`
	// Availability Probes check objects that are part of the package.
	// All probes need to succeed for a package to be considered Available.
	// Failing probes will prevent the reconciliation of objects in later phases.
	AvailabilityProbes []ObjectSetProbeApplyConfiguration `json:"availabilityProbes,omitempty"`
	// Success Delay Seconds applies a wait period from the time an
	// Object Set is available to the time it is marked as successful.
	// This can be used to prevent false reporting of success when
	// the underlying objects may initially satisfy the availability
	// probes, but are ultimately unstable.
	SuccessDelaySeconds *int32 `json:"successDelaySeconds,omitempty"`
}

// ObjectSetTemplateSpecApplyConfiguration constructs a declarative configuration of the ObjectSetTemplateSpec type for use with
// apply.
func ObjectSetTemplateSpec() *ObjectSetTemplateSpecApplyConfiguration {
	return &ObjectSetTemplateSpecApplyConfiguration{}
}

// WithPhases adds the given value to the Phases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Phases field.
func (b *ObjectSetTemplateSpecApplyConfiguration) WithPhases(values ...*ObjectSetTemplatePhaseApplyConfiguration) *ObjectSetTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhases")
		}
		b.Phases = append(b.Phases, *values[i])
	}
	return b
}

// WithAvailabilityProbes adds the given value to the AvailabilityProbes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailabilityProbes field.
func (b *ObjectSetTemplateSpecApplyConfiguration) WithAvailabilityProbes(values ...*ObjectSetProbeApplyConfiguration) *ObjectSetTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAvailabilityProbes")
		}
		b.AvailabilityProbes = append(b.AvailabilityProbes, *values[i])
	}
	return b
}

// WithSuccessDelaySeconds sets the SuccessDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessDelaySeconds field is set to the value of the last call.
func (b *ObjectSetTemplateSpecApplyConfiguration) WithSuccessDelaySeconds(value int32) *ObjectSetTemplateSpecApplyConfiguration {
	b.SuccessDelaySeconds = &value
	return b
}
