// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PackageStatusApplyConfiguration represents a declarative configuration of the PackageStatus type for use
// with apply.
//
// PackageStatus defines the observed state of a Package.
type PackageStatusApplyConfiguration struct {
	// Conditions is a list of status conditions ths object is in.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// Hash of image + config that was successfully unpacked.
	UnpackedHash *string `json:"unpackedHash,omitempty"`
	// Package revision as reported by the ObjectDeployment.
	Revision *int64 `json:"revision,omitempty"`
}

// PackageStatusApplyConfiguration constructs a declarative configuration of the PackageStatus type for use with
// apply.
func PackageStatus() *PackageStatusApplyConfiguration {
	return &PackageStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PackageStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *PackageStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithUnpackedHash sets the UnpackedHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnpackedHash field is set to the value of the last call.
func (b *PackageStatusApplyConfiguration) WithUnpackedHash(value string) *PackageStatusApplyConfiguration {
	b.UnpackedHash = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *PackageStatusApplyConfiguration) WithRevision(value int64) *PackageStatusApplyConfiguration {
	b.Revision = &value
	return b
}
