// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PackageProbeKindSpecApplyConfiguration represents a declarative configuration of the PackageProbeKindSpec type for use
// with apply.
//
// PackageProbeKindSpec package probe parameters.
// selects objects based on Kind and API Group.
type PackageProbeKindSpecApplyConfiguration struct {
	// Object Group to apply a probe to.
	Group *string `json:"group,omitempty"`
	// Object Kind to apply a probe to.
	Kind *string `json:"kind,omitempty"`
}

// PackageProbeKindSpecApplyConfiguration constructs a declarative configuration of the PackageProbeKindSpec type for use with
// apply.
func PackageProbeKindSpec() *PackageProbeKindSpecApplyConfiguration {
	return &PackageProbeKindSpecApplyConfiguration{}
}

// WithGroup sets the Group field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Group field is set to the value of the last call.
func (b *PackageProbeKindSpecApplyConfiguration) WithGroup(value string) *PackageProbeKindSpecApplyConfiguration {
	b.Group = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PackageProbeKindSpecApplyConfiguration) WithKind(value string) *PackageProbeKindSpecApplyConfiguration {
	b.Kind = &value
	return b
}
