// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// PackageSpecApplyConfiguration represents a declarative configuration of the PackageSpec type for use
// with apply.
//
// PackageSpec specifies a package.
type PackageSpecApplyConfiguration struct {
	// the image containing the contents of the package
	// this image will be unpacked by the package-loader to render
	// the ObjectDeployment for propagating the installation of the package.
	Image *string `json:"image,omitempty"`
	// Package configuration parameters.
	Config *runtime.RawExtension `json:"config,omitempty"`
	// Desired component to deploy from multi-component packages.
	Component *string `json:"component,omitempty"`
	// If Paused is true, the package and its children will not be reconciled.
	Paused *bool `json:"paused,omitempty"`
}

// PackageSpecApplyConfiguration constructs a declarative configuration of the PackageSpec type for use with
// apply.
func PackageSpec() *PackageSpecApplyConfiguration {
	return &PackageSpecApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *PackageSpecApplyConfiguration) WithImage(value string) *PackageSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *PackageSpecApplyConfiguration) WithConfig(value runtime.RawExtension) *PackageSpecApplyConfiguration {
	b.Config = &value
	return b
}

// WithComponent sets the Component field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Component field is set to the value of the last call.
func (b *PackageSpecApplyConfiguration) WithComponent(value string) *PackageSpecApplyConfiguration {
	b.Component = &value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *PackageSpecApplyConfiguration) WithPaused(value bool) *PackageSpecApplyConfiguration {
	b.Paused = &value
	return b
}
