// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PreviousRevisionReferenceApplyConfiguration represents a declarative configuration of the PreviousRevisionReference type for use
// with apply.
//
// PreviousRevisionReference references a previous revision of an ObjectSet or ClusterObjectSet.
type PreviousRevisionReferenceApplyConfiguration struct {
	// Name of a previous revision.
	Name *string `json:"name,omitempty"`
}

// PreviousRevisionReferenceApplyConfiguration constructs a declarative configuration of the PreviousRevisionReference type for use with
// apply.
func PreviousRevisionReference() *PreviousRevisionReferenceApplyConfiguration {
	return &PreviousRevisionReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PreviousRevisionReferenceApplyConfiguration) WithName(value string) *PreviousRevisionReferenceApplyConfiguration {
	b.Name = &value
	return b
}
