// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ProbeApplyConfiguration represents a declarative configuration of the Probe type for use
// with apply.
//
// Probe defines probe parameters. Only one can be filled.
type ProbeApplyConfiguration struct {
	Condition   *ProbeConditionSpecApplyConfiguration   `json:"condition,omitempty"`
	FieldsEqual *ProbeFieldsEqualSpecApplyConfiguration `json:"fieldsEqual,omitempty"`
	CEL         *ProbeCELSpecApplyConfiguration         `json:"cel,omitempty"`
}

// ProbeApplyConfiguration constructs a declarative configuration of the Probe type for use with
// apply.
func Probe() *ProbeApplyConfiguration {
	return &ProbeApplyConfiguration{}
}

// WithCondition sets the Condition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Condition field is set to the value of the last call.
func (b *ProbeApplyConfiguration) WithCondition(value *ProbeConditionSpecApplyConfiguration) *ProbeApplyConfiguration {
	b.Condition = value
	return b
}

// WithFieldsEqual sets the FieldsEqual field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldsEqual field is set to the value of the last call.
func (b *ProbeApplyConfiguration) WithFieldsEqual(value *ProbeFieldsEqualSpecApplyConfiguration) *ProbeApplyConfiguration {
	b.FieldsEqual = value
	return b
}

// WithCEL sets the CEL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CEL field is set to the value of the last call.
func (b *ProbeApplyConfiguration) WithCEL(value *ProbeCELSpecApplyConfiguration) *ProbeApplyConfiguration {
	b.CEL = value
	return b
}
