// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ProbeConditionSpecApplyConfiguration represents a declarative configuration of the ProbeConditionSpec type for use
// with apply.
//
// ProbeConditionSpec checks whether or not the object reports a condition with given type and status.
type ProbeConditionSpecApplyConfiguration struct {
	// Condition type to probe for.
	Type *string `json:"type,omitempty"`
	// Condition status to probe for.
	Status *string `json:"status,omitempty"`
}

// ProbeConditionSpecApplyConfiguration constructs a declarative configuration of the ProbeConditionSpec type for use with
// apply.
func ProbeConditionSpec() *ProbeConditionSpecApplyConfiguration {
	return &ProbeConditionSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ProbeConditionSpecApplyConfiguration) WithType(value string) *ProbeConditionSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ProbeConditionSpecApplyConfiguration) WithStatus(value string) *ProbeConditionSpecApplyConfiguration {
	b.Status = &value
	return b
}
