// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ProbeFieldsEqualSpecApplyConfiguration represents a declarative configuration of the ProbeFieldsEqualSpec type for use
// with apply.
//
// ProbeFieldsEqualSpec compares two fields specified by JSON Paths.
type ProbeFieldsEqualSpecApplyConfiguration struct {
	// First field for comparison.
	FieldA *string `json:"fieldA,omitempty"`
	// Second field for comparison.
	FieldB *string `json:"fieldB,omitempty"`
}

// ProbeFieldsEqualSpecApplyConfiguration constructs a declarative configuration of the ProbeFieldsEqualSpec type for use with
// apply.
func ProbeFieldsEqualSpec() *ProbeFieldsEqualSpecApplyConfiguration {
	return &ProbeFieldsEqualSpecApplyConfiguration{}
}

// WithFieldA sets the FieldA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldA field is set to the value of the last call.
func (b *ProbeFieldsEqualSpecApplyConfiguration) WithFieldA(value string) *ProbeFieldsEqualSpecApplyConfiguration {
	b.FieldA = &value
	return b
}

// WithFieldB sets the FieldB field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldB field is set to the value of the last call.
func (b *ProbeFieldsEqualSpecApplyConfiguration) WithFieldB(value string) *ProbeFieldsEqualSpecApplyConfiguration {
	b.FieldB = &value
	return b
}
