// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ProbeCELSpecApplyConfiguration represents a declarative configuration of the ProbeCELSpec type for use
// with apply.
//
// ProbeCELSpec uses Common Expression Language (CEL) to probe an object.
// CEL rules have to evaluate to a boolean to be valid.
// See:
// https://kubernetes.io/docs/reference/using-api/cel
// https://github.com/google/cel-go
type ProbeCELSpecApplyConfiguration struct {
	// CEL rule to evaluate.
	Rule *string `json:"rule,omitempty"`
	// Error message to output if rule evaluates to false.
	Message *string `json:"message,omitempty"`
}

// ProbeCELSpecApplyConfiguration constructs a declarative configuration of the ProbeCELSpec type for use with
// apply.
func ProbeCELSpec() *ProbeCELSpecApplyConfiguration {
	return &ProbeCELSpecApplyConfiguration{}
}

// WithRule sets the Rule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rule field is set to the value of the last call.
func (b *ProbeCELSpecApplyConfiguration) WithRule(value string) *ProbeCELSpecApplyConfiguration {
	b.Rule = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ProbeCELSpecApplyConfiguration) WithMessage(value string) *ProbeCELSpecApplyConfiguration {
	b.Message = &value
	return b
}
