// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// RemotePhaseReferenceApplyConfiguration represents a declarative configuration of the RemotePhaseReference type for use
// with apply.
//
// RemotePhaseReference remote phases aka ObjectSetPhase/ClusterObjectSetPhase objects to which a phase is delegated.
type RemotePhaseReferenceApplyConfiguration struct {
	Name *string    `json:"name,omitempty"`
	UID  *types.UID `json:"uid,omitempty"`
}

// RemotePhaseReferenceApplyConfiguration constructs a declarative configuration of the RemotePhaseReference type for use with
// apply.
func RemotePhaseReference() *RemotePhaseReferenceApplyConfiguration {
	return &RemotePhaseReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RemotePhaseReferenceApplyConfiguration) WithName(value string) *RemotePhaseReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *RemotePhaseReferenceApplyConfiguration) WithUID(value types.UID) *RemotePhaseReferenceApplyConfiguration {
	b.UID = &value
	return b
}
