apiVersion: package-operator.run/v1alpha1
kind: Package
metadata:
  name: "test-frontend"
  annotations:
    package-operator.run/phase: deploy-frontend
    package-operator.run/condition-map: |
      Progressing => my-prefix/Progressing
spec:
  image: whale
  component: frontend
  config:
    testStubImage: dolphin
