//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Adoption) DeepCopyInto(out *Adoption) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Adoption.
func (in *Adoption) DeepCopy() *Adoption {
	if in == nil {
		return nil
	}
	out := new(Adoption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Adoption) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionList) DeepCopyInto(out *AdoptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Adoption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionList.
func (in *AdoptionList) DeepCopy() *AdoptionList {
	if in == nil {
		return nil
	}
	out := new(AdoptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdoptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionRoundRobinStatus) DeepCopyInto(out *AdoptionRoundRobinStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionRoundRobinStatus.
func (in *AdoptionRoundRobinStatus) DeepCopy() *AdoptionRoundRobinStatus {
	if in == nil {
		return nil
	}
	out := new(AdoptionRoundRobinStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionSpec) DeepCopyInto(out *AdoptionSpec) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
	out.TargetAPI = in.TargetAPI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionSpec.
func (in *AdoptionSpec) DeepCopy() *AdoptionSpec {
	if in == nil {
		return nil
	}
	out := new(AdoptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionStatus) DeepCopyInto(out *AdoptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoundRobin != nil {
		in, out := &in.RoundRobin, &out.RoundRobin
		*out = new(AdoptionRoundRobinStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionStatus.
func (in *AdoptionStatus) DeepCopy() *AdoptionStatus {
	if in == nil {
		return nil
	}
	out := new(AdoptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionStrategy) DeepCopyInto(out *AdoptionStrategy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(AdoptionStrategyStaticSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RoundRobin != nil {
		in, out := &in.RoundRobin, &out.RoundRobin
		*out = new(AdoptionStrategyRoundRobinSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionStrategy.
func (in *AdoptionStrategy) DeepCopy() *AdoptionStrategy {
	if in == nil {
		return nil
	}
	out := new(AdoptionStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionStrategyRoundRobinSpec) DeepCopyInto(out *AdoptionStrategyRoundRobinSpec) {
	*out = *in
	if in.Always != nil {
		in, out := &in.Always, &out.Always
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionStrategyRoundRobinSpec.
func (in *AdoptionStrategyRoundRobinSpec) DeepCopy() *AdoptionStrategyRoundRobinSpec {
	if in == nil {
		return nil
	}
	out := new(AdoptionStrategyRoundRobinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionStrategyStaticSpec) DeepCopyInto(out *AdoptionStrategyStaticSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionStrategyStaticSpec.
func (in *AdoptionStrategyStaticSpec) DeepCopy() *AdoptionStrategyStaticSpec {
	if in == nil {
		return nil
	}
	out := new(AdoptionStrategyStaticSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdoption) DeepCopyInto(out *ClusterAdoption) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdoption.
func (in *ClusterAdoption) DeepCopy() *ClusterAdoption {
	if in == nil {
		return nil
	}
	out := new(ClusterAdoption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAdoption) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdoptionList) DeepCopyInto(out *ClusterAdoptionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterAdoption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdoptionList.
func (in *ClusterAdoptionList) DeepCopy() *ClusterAdoptionList {
	if in == nil {
		return nil
	}
	out := new(ClusterAdoptionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterAdoptionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdoptionSpec) DeepCopyInto(out *ClusterAdoptionSpec) {
	*out = *in
	in.Strategy.DeepCopyInto(&out.Strategy)
	out.TargetAPI = in.TargetAPI
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdoptionSpec.
func (in *ClusterAdoptionSpec) DeepCopy() *ClusterAdoptionSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterAdoptionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdoptionStatus) DeepCopyInto(out *ClusterAdoptionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RoundRobin != nil {
		in, out := &in.RoundRobin, &out.RoundRobin
		*out = new(AdoptionRoundRobinStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdoptionStatus.
func (in *ClusterAdoptionStatus) DeepCopy() *ClusterAdoptionStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterAdoptionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterAdoptionStrategy) DeepCopyInto(out *ClusterAdoptionStrategy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(AdoptionStrategyStaticSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RoundRobin != nil {
		in, out := &in.RoundRobin, &out.RoundRobin
		*out = new(AdoptionStrategyRoundRobinSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterAdoptionStrategy.
func (in *ClusterAdoptionStrategy) DeepCopy() *ClusterAdoptionStrategy {
	if in == nil {
		return nil
	}
	out := new(ClusterAdoptionStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetAPI) DeepCopyInto(out *TargetAPI) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetAPI.
func (in *TargetAPI) DeepCopy() *TargetAPI {
	if in == nil {
		return nil
	}
	out := new(TargetAPI)
	in.DeepCopyInto(out)
	return out
}
