// Code generated by controller-gen. DO NOT EDIT.

package applyconfigurations

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	corev1alpha1 "package-operator.run/apis/applyconfigurations/core/v1alpha1"
	internal "package-operator.run/apis/applyconfigurations/internal"
	v1alpha1 "package-operator.run/apis/core/v1alpha1"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=package-operator.run, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeployment"):
		return &corev1alpha1.ClusterObjectDeploymentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentSpec"):
		return &corev1alpha1.ClusterObjectDeploymentSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectDeploymentStatus"):
		return &corev1alpha1.ClusterObjectDeploymentStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSet"):
		return &corev1alpha1.ClusterObjectSetApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetPhase"):
		return &corev1alpha1.ClusterObjectSetPhaseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetPhaseSpec"):
		return &corev1alpha1.ClusterObjectSetPhaseSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetPhaseStatus"):
		return &corev1alpha1.ClusterObjectSetPhaseStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetSpec"):
		return &corev1alpha1.ClusterObjectSetSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSetStatus"):
		return &corev1alpha1.ClusterObjectSetStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectSlice"):
		return &corev1alpha1.ClusterObjectSliceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterObjectTemplate"):
		return &corev1alpha1.ClusterObjectTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterPackage"):
		return &corev1alpha1.ClusterPackageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ConditionMapping"):
		return &corev1alpha1.ConditionMappingApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ControlledObjectReference"):
		return &corev1alpha1.ControlledObjectReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackage"):
		return &corev1alpha1.HostedClusterPackageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackageCountsStatus"):
		return &corev1alpha1.HostedClusterPackageCountsStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackagePartitionOrderSpec"):
		return &corev1alpha1.HostedClusterPackagePartitionOrderSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackagePartitionSpec"):
		return &corev1alpha1.HostedClusterPackagePartitionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackagePartitionStatus"):
		return &corev1alpha1.HostedClusterPackagePartitionStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackageRefStatus"):
		return &corev1alpha1.HostedClusterPackageRefStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackageSpec"):
		return &corev1alpha1.HostedClusterPackageSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackageStatus"):
		return &corev1alpha1.HostedClusterPackageStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackageStrategy"):
		return &corev1alpha1.HostedClusterPackageStrategyApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("HostedClusterPackageStrategyRollingUpgrade"):
		return &corev1alpha1.HostedClusterPackageStrategyRollingUpgradeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectDeployment"):
		return &corev1alpha1.ObjectDeploymentApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectDeploymentSpec"):
		return &corev1alpha1.ObjectDeploymentSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectDeploymentStatus"):
		return &corev1alpha1.ObjectDeploymentStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSet"):
		return &corev1alpha1.ObjectSetApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetObject"):
		return &corev1alpha1.ObjectSetObjectApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetPhase"):
		return &corev1alpha1.ObjectSetPhaseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetPhaseSpec"):
		return &corev1alpha1.ObjectSetPhaseSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetPhaseStatus"):
		return &corev1alpha1.ObjectSetPhaseStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetProbe"):
		return &corev1alpha1.ObjectSetProbeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetSpec"):
		return &corev1alpha1.ObjectSetSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetStatus"):
		return &corev1alpha1.ObjectSetStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetTemplate"):
		return &corev1alpha1.ObjectSetTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetTemplatePhase"):
		return &corev1alpha1.ObjectSetTemplatePhaseApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectSetTemplateSpec"):
		return &corev1alpha1.ObjectSetTemplateSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectTemplate"):
		return &corev1alpha1.ObjectTemplateApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectTemplateSource"):
		return &corev1alpha1.ObjectTemplateSourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectTemplateSourceItem"):
		return &corev1alpha1.ObjectTemplateSourceItemApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectTemplateSpec"):
		return &corev1alpha1.ObjectTemplateSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ObjectTemplateStatus"):
		return &corev1alpha1.ObjectTemplateStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Package"):
		return &corev1alpha1.PackageApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PackageProbeKindSpec"):
		return &corev1alpha1.PackageProbeKindSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PackageSpec"):
		return &corev1alpha1.PackageSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PackageStatus"):
		return &corev1alpha1.PackageStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PackageTemplateSpec"):
		return &corev1alpha1.PackageTemplateSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("PreviousRevisionReference"):
		return &corev1alpha1.PreviousRevisionReferenceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Probe"):
		return &corev1alpha1.ProbeApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProbeCELSpec"):
		return &corev1alpha1.ProbeCELSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProbeConditionSpec"):
		return &corev1alpha1.ProbeConditionSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProbeFieldsEqualSpec"):
		return &corev1alpha1.ProbeFieldsEqualSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ProbeSelector"):
		return &corev1alpha1.ProbeSelectorApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RemotePhaseReference"):
		return &corev1alpha1.RemotePhaseReferenceApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
