{
 "title": "Package Operator",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Packages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (package_operator_package_availability)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Packages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (package_operator_package_availability==1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Packages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count by(pko_name, pko_namespace) (package_operator_package_availability==0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total ObjectSets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (package_operator_object_set_created_timestamp_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Succeeded ObjectSets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (package_operator_object_set_succeeded_timestamp_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archived ObjectSets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (package_operator_object_set_created_timestamp_seconds) - count (package_operator_object_set_succeeded_timestamp_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(pko_name, pko_namespace) (package_operator_package_availability{pko_name=\"package-operator\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Revisions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(package_operator_package_revision{pko_name=\"package-operator\",pko_namespace=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollout",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  max by (pko_package_instance, pko_namespace) (package_operator_object_set_succeeded_timestamp_seconds{pko_package_instance=\"package-operator\",pko_namespace=\"\"})\n- on (pko_package_instance, pko_namespace)\n  max by (pko_package_instance, pko_namespace) (package_operator_object_set_created_timestamp_seconds{pko_package_instance=\"package-operator\",pko_namespace=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Package Load Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (package_operator_package_load_duration_milliseconds)",
     "legendFormat": "{{pko_namespace}}/{{pko_name}}"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Avg Queue Duration",
   "type": "bargauge",
   "description": "How long in seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(name) (workqueue_queue_duration_seconds_bucket{service=\"package-operator-metrics\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Avg Reconcile Duration",
   "type": "bargauge",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(controller) (controller_runtime_reconcile_time_seconds_bucket{service=\"package-operator-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reconcile Errors",
   "type": "bargauge",
   "description": "Rate of reconciliation errors per controller.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(controller) (rate(controller_runtime_reconcile_errors_total{service=\"package-operator-metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilized Workers",
   "type": "bargauge",
   "description": "Rate of reconciliation errors per controller.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(controller) (controller_runtime_active_workers{service=\"package-operator-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Dynamic Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Dynamic Cache by GVK",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 20, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg by(pko_gvk) (package_operator_dynamic_cache_objects)",
     "legendFormat": "{{pko_gvk}}"
    }
   ]
  },
  {
   "title": "Dynamic Cache Informer Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(package_operator_dynamic_cache_informers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Objects Cached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(package_operator_dynamic_cache_objects)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "state-timeline",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by(pko_name, pko_namespace) (package_operator_package_availability{pko_name!=\"package-operator\"})",
       "legendFormat": "{{pko_namespace}}/{{pko_name}}"
      }
     ]
    },
    {
     "title": "Revision Rollout Time",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 4, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  max by (pko_package_instance, pko_namespace) (package_operator_object_set_succeeded_timestamp_seconds{pko_package_instance!=\"package-operator\"})\n- on (pko_package_instance, pko_namespace)\n  max by (pko_package_instance, pko_namespace) (package_operator_object_set_created_timestamp_seconds{pko_package_instance!=\"package-operator\"})",
       "legendFormat": "{{pko_namespace}}/{{pko_package_instance}}"
      }
     ]
    }
   ]
  }
 ]
}