// +k8s:conversion-gen=package-operator.run/apis/manifests/v1alpha1
package manifests

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
)

// Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps is an autogenerated conversion function.
//
//nolint:revive,lll
func Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(in *apiextensionsv1.JSONSchemaProps, out *apiextensions.JSONSchemaProps, s conversion.Scope) error {
	return apiextensionsv1.Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(in, out, s)
}
