//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package manifests

import (
	unsafe "unsafe"

	apiextensions "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions"
	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	corev1alpha1 "package-operator.run/apis/core/v1alpha1"
	v1alpha1 "package-operator.run/apis/manifests/v1alpha1"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PackageEnvironment)(nil), (*v1alpha1.PackageEnvironment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageEnvironment_To_v1alpha1_PackageEnvironment(a.(*PackageEnvironment), b.(*v1alpha1.PackageEnvironment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageEnvironment)(nil), (*PackageEnvironment)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageEnvironment_To_manifests_PackageEnvironment(a.(*v1alpha1.PackageEnvironment), b.(*PackageEnvironment), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageEnvironmentKubernetes)(nil), (*v1alpha1.PackageEnvironmentKubernetes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageEnvironmentKubernetes_To_v1alpha1_PackageEnvironmentKubernetes(a.(*PackageEnvironmentKubernetes), b.(*v1alpha1.PackageEnvironmentKubernetes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageEnvironmentKubernetes)(nil), (*PackageEnvironmentKubernetes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageEnvironmentKubernetes_To_manifests_PackageEnvironmentKubernetes(a.(*v1alpha1.PackageEnvironmentKubernetes), b.(*PackageEnvironmentKubernetes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageEnvironmentOpenShift)(nil), (*v1alpha1.PackageEnvironmentOpenShift)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageEnvironmentOpenShift_To_v1alpha1_PackageEnvironmentOpenShift(a.(*PackageEnvironmentOpenShift), b.(*v1alpha1.PackageEnvironmentOpenShift), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageEnvironmentOpenShift)(nil), (*PackageEnvironmentOpenShift)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageEnvironmentOpenShift_To_manifests_PackageEnvironmentOpenShift(a.(*v1alpha1.PackageEnvironmentOpenShift), b.(*PackageEnvironmentOpenShift), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageEnvironmentProxy)(nil), (*v1alpha1.PackageEnvironmentProxy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageEnvironmentProxy_To_v1alpha1_PackageEnvironmentProxy(a.(*PackageEnvironmentProxy), b.(*v1alpha1.PackageEnvironmentProxy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageEnvironmentProxy)(nil), (*PackageEnvironmentProxy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageEnvironmentProxy_To_manifests_PackageEnvironmentProxy(a.(*v1alpha1.PackageEnvironmentProxy), b.(*PackageEnvironmentProxy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifest)(nil), (*v1alpha1.PackageManifest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifest_To_v1alpha1_PackageManifest(a.(*PackageManifest), b.(*v1alpha1.PackageManifest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifest)(nil), (*PackageManifest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifest_To_manifests_PackageManifest(a.(*v1alpha1.PackageManifest), b.(*PackageManifest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestComponentsConfig)(nil), (*v1alpha1.PackageManifestComponentsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestComponentsConfig_To_v1alpha1_PackageManifestComponentsConfig(a.(*PackageManifestComponentsConfig), b.(*v1alpha1.PackageManifestComponentsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestComponentsConfig)(nil), (*PackageManifestComponentsConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestComponentsConfig_To_manifests_PackageManifestComponentsConfig(a.(*v1alpha1.PackageManifestComponentsConfig), b.(*PackageManifestComponentsConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestConstraint)(nil), (*v1alpha1.PackageManifestConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestConstraint_To_v1alpha1_PackageManifestConstraint(a.(*PackageManifestConstraint), b.(*v1alpha1.PackageManifestConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestConstraint)(nil), (*PackageManifestConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestConstraint_To_manifests_PackageManifestConstraint(a.(*v1alpha1.PackageManifestConstraint), b.(*PackageManifestConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestDependency)(nil), (*v1alpha1.PackageManifestDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestDependency_To_v1alpha1_PackageManifestDependency(a.(*PackageManifestDependency), b.(*v1alpha1.PackageManifestDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestDependency)(nil), (*PackageManifestDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestDependency_To_manifests_PackageManifestDependency(a.(*v1alpha1.PackageManifestDependency), b.(*PackageManifestDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestDependencyImage)(nil), (*v1alpha1.PackageManifestDependencyImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestDependencyImage_To_v1alpha1_PackageManifestDependencyImage(a.(*PackageManifestDependencyImage), b.(*v1alpha1.PackageManifestDependencyImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestDependencyImage)(nil), (*PackageManifestDependencyImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestDependencyImage_To_manifests_PackageManifestDependencyImage(a.(*v1alpha1.PackageManifestDependencyImage), b.(*PackageManifestDependencyImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestImage)(nil), (*v1alpha1.PackageManifestImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestImage_To_v1alpha1_PackageManifestImage(a.(*PackageManifestImage), b.(*v1alpha1.PackageManifestImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestImage)(nil), (*PackageManifestImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestImage_To_manifests_PackageManifestImage(a.(*v1alpha1.PackageManifestImage), b.(*PackageManifestImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestLock)(nil), (*v1alpha1.PackageManifestLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestLock_To_v1alpha1_PackageManifestLock(a.(*PackageManifestLock), b.(*v1alpha1.PackageManifestLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestLock)(nil), (*PackageManifestLock)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestLock_To_manifests_PackageManifestLock(a.(*v1alpha1.PackageManifestLock), b.(*PackageManifestLock), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestLockDependency)(nil), (*v1alpha1.PackageManifestLockDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestLockDependency_To_v1alpha1_PackageManifestLockDependency(a.(*PackageManifestLockDependency), b.(*v1alpha1.PackageManifestLockDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestLockDependency)(nil), (*PackageManifestLockDependency)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestLockDependency_To_manifests_PackageManifestLockDependency(a.(*v1alpha1.PackageManifestLockDependency), b.(*PackageManifestLockDependency), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestLockImage)(nil), (*v1alpha1.PackageManifestLockImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestLockImage_To_v1alpha1_PackageManifestLockImage(a.(*PackageManifestLockImage), b.(*v1alpha1.PackageManifestLockImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestLockImage)(nil), (*PackageManifestLockImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestLockImage_To_manifests_PackageManifestLockImage(a.(*v1alpha1.PackageManifestLockImage), b.(*PackageManifestLockImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestLockSpec)(nil), (*v1alpha1.PackageManifestLockSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestLockSpec_To_v1alpha1_PackageManifestLockSpec(a.(*PackageManifestLockSpec), b.(*v1alpha1.PackageManifestLockSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestLockSpec)(nil), (*PackageManifestLockSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestLockSpec_To_manifests_PackageManifestLockSpec(a.(*v1alpha1.PackageManifestLockSpec), b.(*PackageManifestLockSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestPhase)(nil), (*v1alpha1.PackageManifestPhase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestPhase_To_v1alpha1_PackageManifestPhase(a.(*PackageManifestPhase), b.(*v1alpha1.PackageManifestPhase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestPhase)(nil), (*PackageManifestPhase)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestPhase_To_manifests_PackageManifestPhase(a.(*v1alpha1.PackageManifestPhase), b.(*PackageManifestPhase), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestPlatformVersionConstraint)(nil), (*v1alpha1.PackageManifestPlatformVersionConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestPlatformVersionConstraint_To_v1alpha1_PackageManifestPlatformVersionConstraint(a.(*PackageManifestPlatformVersionConstraint), b.(*v1alpha1.PackageManifestPlatformVersionConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestPlatformVersionConstraint)(nil), (*PackageManifestPlatformVersionConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestPlatformVersionConstraint_To_manifests_PackageManifestPlatformVersionConstraint(a.(*v1alpha1.PackageManifestPlatformVersionConstraint), b.(*PackageManifestPlatformVersionConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestRepository)(nil), (*v1alpha1.PackageManifestRepository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestRepository_To_v1alpha1_PackageManifestRepository(a.(*PackageManifestRepository), b.(*v1alpha1.PackageManifestRepository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestRepository)(nil), (*PackageManifestRepository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestRepository_To_manifests_PackageManifestRepository(a.(*v1alpha1.PackageManifestRepository), b.(*PackageManifestRepository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestSpec)(nil), (*v1alpha1.PackageManifestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestSpec_To_v1alpha1_PackageManifestSpec(a.(*PackageManifestSpec), b.(*v1alpha1.PackageManifestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestSpec)(nil), (*PackageManifestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestSpec_To_manifests_PackageManifestSpec(a.(*v1alpha1.PackageManifestSpec), b.(*PackageManifestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestSpecConfig)(nil), (*v1alpha1.PackageManifestSpecConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestSpecConfig_To_v1alpha1_PackageManifestSpecConfig(a.(*PackageManifestSpecConfig), b.(*v1alpha1.PackageManifestSpecConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestSpecConfig)(nil), (*PackageManifestSpecConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestSpecConfig_To_manifests_PackageManifestSpecConfig(a.(*v1alpha1.PackageManifestSpecConfig), b.(*PackageManifestSpecConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestTest)(nil), (*v1alpha1.PackageManifestTest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestTest_To_v1alpha1_PackageManifestTest(a.(*PackageManifestTest), b.(*v1alpha1.PackageManifestTest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestTest)(nil), (*PackageManifestTest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestTest_To_manifests_PackageManifestTest(a.(*v1alpha1.PackageManifestTest), b.(*PackageManifestTest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestTestCaseTemplate)(nil), (*v1alpha1.PackageManifestTestCaseTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestTestCaseTemplate_To_v1alpha1_PackageManifestTestCaseTemplate(a.(*PackageManifestTestCaseTemplate), b.(*v1alpha1.PackageManifestTestCaseTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestTestCaseTemplate)(nil), (*PackageManifestTestCaseTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestTestCaseTemplate_To_manifests_PackageManifestTestCaseTemplate(a.(*v1alpha1.PackageManifestTestCaseTemplate), b.(*PackageManifestTestCaseTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestTestKubeconform)(nil), (*v1alpha1.PackageManifestTestKubeconform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestTestKubeconform_To_v1alpha1_PackageManifestTestKubeconform(a.(*PackageManifestTestKubeconform), b.(*v1alpha1.PackageManifestTestKubeconform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestTestKubeconform)(nil), (*PackageManifestTestKubeconform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestTestKubeconform_To_manifests_PackageManifestTestKubeconform(a.(*v1alpha1.PackageManifestTestKubeconform), b.(*PackageManifestTestKubeconform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PackageManifestUniqueInScopeConstraint)(nil), (*v1alpha1.PackageManifestUniqueInScopeConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_PackageManifestUniqueInScopeConstraint_To_v1alpha1_PackageManifestUniqueInScopeConstraint(a.(*PackageManifestUniqueInScopeConstraint), b.(*v1alpha1.PackageManifestUniqueInScopeConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.PackageManifestUniqueInScopeConstraint)(nil), (*PackageManifestUniqueInScopeConstraint)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PackageManifestUniqueInScopeConstraint_To_manifests_PackageManifestUniqueInScopeConstraint(a.(*v1alpha1.PackageManifestUniqueInScopeConstraint), b.(*PackageManifestUniqueInScopeConstraint), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Repository)(nil), (*v1alpha1.Repository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_Repository_To_v1alpha1_Repository(a.(*Repository), b.(*v1alpha1.Repository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.Repository)(nil), (*Repository)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Repository_To_manifests_Repository(a.(*v1alpha1.Repository), b.(*Repository), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepositoryEntry)(nil), (*v1alpha1.RepositoryEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_RepositoryEntry_To_v1alpha1_RepositoryEntry(a.(*RepositoryEntry), b.(*v1alpha1.RepositoryEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RepositoryEntry)(nil), (*RepositoryEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositoryEntry_To_manifests_RepositoryEntry(a.(*v1alpha1.RepositoryEntry), b.(*RepositoryEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RepositoryEntryData)(nil), (*v1alpha1.RepositoryEntryData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_RepositoryEntryData_To_v1alpha1_RepositoryEntryData(a.(*RepositoryEntryData), b.(*v1alpha1.RepositoryEntryData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.RepositoryEntryData)(nil), (*RepositoryEntryData)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RepositoryEntryData_To_manifests_RepositoryEntryData(a.(*v1alpha1.RepositoryEntryData), b.(*RepositoryEntryData), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateContext)(nil), (*v1alpha1.TemplateContext)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_TemplateContext_To_v1alpha1_TemplateContext(a.(*TemplateContext), b.(*v1alpha1.TemplateContext), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.TemplateContext)(nil), (*TemplateContext)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateContext_To_manifests_TemplateContext(a.(*v1alpha1.TemplateContext), b.(*TemplateContext), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateContextObjectMeta)(nil), (*v1alpha1.TemplateContextObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_TemplateContextObjectMeta_To_v1alpha1_TemplateContextObjectMeta(a.(*TemplateContextObjectMeta), b.(*v1alpha1.TemplateContextObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.TemplateContextObjectMeta)(nil), (*TemplateContextObjectMeta)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateContextObjectMeta_To_manifests_TemplateContextObjectMeta(a.(*v1alpha1.TemplateContextObjectMeta), b.(*TemplateContextObjectMeta), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateContextPackage)(nil), (*v1alpha1.TemplateContextPackage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_manifests_TemplateContextPackage_To_v1alpha1_TemplateContextPackage(a.(*TemplateContextPackage), b.(*v1alpha1.TemplateContextPackage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1alpha1.TemplateContextPackage)(nil), (*TemplateContextPackage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateContextPackage_To_manifests_TemplateContextPackage(a.(*v1alpha1.TemplateContextPackage), b.(*TemplateContextPackage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*v1.JSONSchemaProps)(nil), (*apiextensions.JSONSchemaProps)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(a.(*v1.JSONSchemaProps), b.(*apiextensions.JSONSchemaProps), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_manifests_PackageEnvironment_To_v1alpha1_PackageEnvironment(in *PackageEnvironment, out *v1alpha1.PackageEnvironment, s conversion.Scope) error {
	if err := Convert_manifests_PackageEnvironmentKubernetes_To_v1alpha1_PackageEnvironmentKubernetes(&in.Kubernetes, &out.Kubernetes, s); err != nil {
		return err
	}
	out.OpenShift = (*v1alpha1.PackageEnvironmentOpenShift)(unsafe.Pointer(in.OpenShift))
	out.Proxy = (*v1alpha1.PackageEnvironmentProxy)(unsafe.Pointer(in.Proxy))
	return nil
}

// Convert_manifests_PackageEnvironment_To_v1alpha1_PackageEnvironment is an autogenerated conversion function.
func Convert_manifests_PackageEnvironment_To_v1alpha1_PackageEnvironment(in *PackageEnvironment, out *v1alpha1.PackageEnvironment, s conversion.Scope) error {
	return autoConvert_manifests_PackageEnvironment_To_v1alpha1_PackageEnvironment(in, out, s)
}

func autoConvert_v1alpha1_PackageEnvironment_To_manifests_PackageEnvironment(in *v1alpha1.PackageEnvironment, out *PackageEnvironment, s conversion.Scope) error {
	if err := Convert_v1alpha1_PackageEnvironmentKubernetes_To_manifests_PackageEnvironmentKubernetes(&in.Kubernetes, &out.Kubernetes, s); err != nil {
		return err
	}
	out.OpenShift = (*PackageEnvironmentOpenShift)(unsafe.Pointer(in.OpenShift))
	out.Proxy = (*PackageEnvironmentProxy)(unsafe.Pointer(in.Proxy))
	return nil
}

// Convert_v1alpha1_PackageEnvironment_To_manifests_PackageEnvironment is an autogenerated conversion function.
func Convert_v1alpha1_PackageEnvironment_To_manifests_PackageEnvironment(in *v1alpha1.PackageEnvironment, out *PackageEnvironment, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageEnvironment_To_manifests_PackageEnvironment(in, out, s)
}

func autoConvert_manifests_PackageEnvironmentKubernetes_To_v1alpha1_PackageEnvironmentKubernetes(in *PackageEnvironmentKubernetes, out *v1alpha1.PackageEnvironmentKubernetes, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_manifests_PackageEnvironmentKubernetes_To_v1alpha1_PackageEnvironmentKubernetes is an autogenerated conversion function.
func Convert_manifests_PackageEnvironmentKubernetes_To_v1alpha1_PackageEnvironmentKubernetes(in *PackageEnvironmentKubernetes, out *v1alpha1.PackageEnvironmentKubernetes, s conversion.Scope) error {
	return autoConvert_manifests_PackageEnvironmentKubernetes_To_v1alpha1_PackageEnvironmentKubernetes(in, out, s)
}

func autoConvert_v1alpha1_PackageEnvironmentKubernetes_To_manifests_PackageEnvironmentKubernetes(in *v1alpha1.PackageEnvironmentKubernetes, out *PackageEnvironmentKubernetes, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_PackageEnvironmentKubernetes_To_manifests_PackageEnvironmentKubernetes is an autogenerated conversion function.
func Convert_v1alpha1_PackageEnvironmentKubernetes_To_manifests_PackageEnvironmentKubernetes(in *v1alpha1.PackageEnvironmentKubernetes, out *PackageEnvironmentKubernetes, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageEnvironmentKubernetes_To_manifests_PackageEnvironmentKubernetes(in, out, s)
}

func autoConvert_manifests_PackageEnvironmentOpenShift_To_v1alpha1_PackageEnvironmentOpenShift(in *PackageEnvironmentOpenShift, out *v1alpha1.PackageEnvironmentOpenShift, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_manifests_PackageEnvironmentOpenShift_To_v1alpha1_PackageEnvironmentOpenShift is an autogenerated conversion function.
func Convert_manifests_PackageEnvironmentOpenShift_To_v1alpha1_PackageEnvironmentOpenShift(in *PackageEnvironmentOpenShift, out *v1alpha1.PackageEnvironmentOpenShift, s conversion.Scope) error {
	return autoConvert_manifests_PackageEnvironmentOpenShift_To_v1alpha1_PackageEnvironmentOpenShift(in, out, s)
}

func autoConvert_v1alpha1_PackageEnvironmentOpenShift_To_manifests_PackageEnvironmentOpenShift(in *v1alpha1.PackageEnvironmentOpenShift, out *PackageEnvironmentOpenShift, s conversion.Scope) error {
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_PackageEnvironmentOpenShift_To_manifests_PackageEnvironmentOpenShift is an autogenerated conversion function.
func Convert_v1alpha1_PackageEnvironmentOpenShift_To_manifests_PackageEnvironmentOpenShift(in *v1alpha1.PackageEnvironmentOpenShift, out *PackageEnvironmentOpenShift, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageEnvironmentOpenShift_To_manifests_PackageEnvironmentOpenShift(in, out, s)
}

func autoConvert_manifests_PackageEnvironmentProxy_To_v1alpha1_PackageEnvironmentProxy(in *PackageEnvironmentProxy, out *v1alpha1.PackageEnvironmentProxy, s conversion.Scope) error {
	out.HTTPProxy = in.HTTPProxy
	out.HTTPSProxy = in.HTTPSProxy
	out.NoProxy = in.NoProxy
	return nil
}

// Convert_manifests_PackageEnvironmentProxy_To_v1alpha1_PackageEnvironmentProxy is an autogenerated conversion function.
func Convert_manifests_PackageEnvironmentProxy_To_v1alpha1_PackageEnvironmentProxy(in *PackageEnvironmentProxy, out *v1alpha1.PackageEnvironmentProxy, s conversion.Scope) error {
	return autoConvert_manifests_PackageEnvironmentProxy_To_v1alpha1_PackageEnvironmentProxy(in, out, s)
}

func autoConvert_v1alpha1_PackageEnvironmentProxy_To_manifests_PackageEnvironmentProxy(in *v1alpha1.PackageEnvironmentProxy, out *PackageEnvironmentProxy, s conversion.Scope) error {
	out.HTTPProxy = in.HTTPProxy
	out.HTTPSProxy = in.HTTPSProxy
	out.NoProxy = in.NoProxy
	return nil
}

// Convert_v1alpha1_PackageEnvironmentProxy_To_manifests_PackageEnvironmentProxy is an autogenerated conversion function.
func Convert_v1alpha1_PackageEnvironmentProxy_To_manifests_PackageEnvironmentProxy(in *v1alpha1.PackageEnvironmentProxy, out *PackageEnvironmentProxy, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageEnvironmentProxy_To_manifests_PackageEnvironmentProxy(in, out, s)
}

func autoConvert_manifests_PackageManifest_To_v1alpha1_PackageManifest(in *PackageManifest, out *v1alpha1.PackageManifest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_manifests_PackageManifestSpec_To_v1alpha1_PackageManifestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_manifests_PackageManifestTest_To_v1alpha1_PackageManifestTest(&in.Test, &out.Test, s); err != nil {
		return err
	}
	return nil
}

// Convert_manifests_PackageManifest_To_v1alpha1_PackageManifest is an autogenerated conversion function.
func Convert_manifests_PackageManifest_To_v1alpha1_PackageManifest(in *PackageManifest, out *v1alpha1.PackageManifest, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifest_To_v1alpha1_PackageManifest(in, out, s)
}

func autoConvert_v1alpha1_PackageManifest_To_manifests_PackageManifest(in *v1alpha1.PackageManifest, out *PackageManifest, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PackageManifestSpec_To_manifests_PackageManifestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_PackageManifestTest_To_manifests_PackageManifestTest(&in.Test, &out.Test, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PackageManifest_To_manifests_PackageManifest is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifest_To_manifests_PackageManifest(in *v1alpha1.PackageManifest, out *PackageManifest, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifest_To_manifests_PackageManifest(in, out, s)
}

func autoConvert_manifests_PackageManifestComponentsConfig_To_v1alpha1_PackageManifestComponentsConfig(in *PackageManifestComponentsConfig, out *v1alpha1.PackageManifestComponentsConfig, s conversion.Scope) error {
	return nil
}

// Convert_manifests_PackageManifestComponentsConfig_To_v1alpha1_PackageManifestComponentsConfig is an autogenerated conversion function.
func Convert_manifests_PackageManifestComponentsConfig_To_v1alpha1_PackageManifestComponentsConfig(in *PackageManifestComponentsConfig, out *v1alpha1.PackageManifestComponentsConfig, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestComponentsConfig_To_v1alpha1_PackageManifestComponentsConfig(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestComponentsConfig_To_manifests_PackageManifestComponentsConfig(in *v1alpha1.PackageManifestComponentsConfig, out *PackageManifestComponentsConfig, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_PackageManifestComponentsConfig_To_manifests_PackageManifestComponentsConfig is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestComponentsConfig_To_manifests_PackageManifestComponentsConfig(in *v1alpha1.PackageManifestComponentsConfig, out *PackageManifestComponentsConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestComponentsConfig_To_manifests_PackageManifestComponentsConfig(in, out, s)
}

func autoConvert_manifests_PackageManifestConstraint_To_v1alpha1_PackageManifestConstraint(in *PackageManifestConstraint, out *v1alpha1.PackageManifestConstraint, s conversion.Scope) error {
	out.PlatformVersion = (*v1alpha1.PackageManifestPlatformVersionConstraint)(unsafe.Pointer(in.PlatformVersion))
	out.Platform = *(*[]v1alpha1.PlatformName)(unsafe.Pointer(&in.Platform))
	out.UniqueInScope = (*v1alpha1.PackageManifestUniqueInScopeConstraint)(unsafe.Pointer(in.UniqueInScope))
	return nil
}

// Convert_manifests_PackageManifestConstraint_To_v1alpha1_PackageManifestConstraint is an autogenerated conversion function.
func Convert_manifests_PackageManifestConstraint_To_v1alpha1_PackageManifestConstraint(in *PackageManifestConstraint, out *v1alpha1.PackageManifestConstraint, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestConstraint_To_v1alpha1_PackageManifestConstraint(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestConstraint_To_manifests_PackageManifestConstraint(in *v1alpha1.PackageManifestConstraint, out *PackageManifestConstraint, s conversion.Scope) error {
	out.PlatformVersion = (*PackageManifestPlatformVersionConstraint)(unsafe.Pointer(in.PlatformVersion))
	out.Platform = *(*[]PlatformName)(unsafe.Pointer(&in.Platform))
	out.UniqueInScope = (*PackageManifestUniqueInScopeConstraint)(unsafe.Pointer(in.UniqueInScope))
	return nil
}

// Convert_v1alpha1_PackageManifestConstraint_To_manifests_PackageManifestConstraint is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestConstraint_To_manifests_PackageManifestConstraint(in *v1alpha1.PackageManifestConstraint, out *PackageManifestConstraint, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestConstraint_To_manifests_PackageManifestConstraint(in, out, s)
}

func autoConvert_manifests_PackageManifestDependency_To_v1alpha1_PackageManifestDependency(in *PackageManifestDependency, out *v1alpha1.PackageManifestDependency, s conversion.Scope) error {
	out.Image = (*v1alpha1.PackageManifestDependencyImage)(unsafe.Pointer(in.Image))
	return nil
}

// Convert_manifests_PackageManifestDependency_To_v1alpha1_PackageManifestDependency is an autogenerated conversion function.
func Convert_manifests_PackageManifestDependency_To_v1alpha1_PackageManifestDependency(in *PackageManifestDependency, out *v1alpha1.PackageManifestDependency, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestDependency_To_v1alpha1_PackageManifestDependency(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestDependency_To_manifests_PackageManifestDependency(in *v1alpha1.PackageManifestDependency, out *PackageManifestDependency, s conversion.Scope) error {
	out.Image = (*PackageManifestDependencyImage)(unsafe.Pointer(in.Image))
	return nil
}

// Convert_v1alpha1_PackageManifestDependency_To_manifests_PackageManifestDependency is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestDependency_To_manifests_PackageManifestDependency(in *v1alpha1.PackageManifestDependency, out *PackageManifestDependency, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestDependency_To_manifests_PackageManifestDependency(in, out, s)
}

func autoConvert_manifests_PackageManifestDependencyImage_To_v1alpha1_PackageManifestDependencyImage(in *PackageManifestDependencyImage, out *v1alpha1.PackageManifestDependencyImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Package = in.Package
	out.Range = in.Range
	return nil
}

// Convert_manifests_PackageManifestDependencyImage_To_v1alpha1_PackageManifestDependencyImage is an autogenerated conversion function.
func Convert_manifests_PackageManifestDependencyImage_To_v1alpha1_PackageManifestDependencyImage(in *PackageManifestDependencyImage, out *v1alpha1.PackageManifestDependencyImage, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestDependencyImage_To_v1alpha1_PackageManifestDependencyImage(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestDependencyImage_To_manifests_PackageManifestDependencyImage(in *v1alpha1.PackageManifestDependencyImage, out *PackageManifestDependencyImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Package = in.Package
	out.Range = in.Range
	return nil
}

// Convert_v1alpha1_PackageManifestDependencyImage_To_manifests_PackageManifestDependencyImage is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestDependencyImage_To_manifests_PackageManifestDependencyImage(in *v1alpha1.PackageManifestDependencyImage, out *PackageManifestDependencyImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestDependencyImage_To_manifests_PackageManifestDependencyImage(in, out, s)
}

func autoConvert_manifests_PackageManifestImage_To_v1alpha1_PackageManifestImage(in *PackageManifestImage, out *v1alpha1.PackageManifestImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	return nil
}

// Convert_manifests_PackageManifestImage_To_v1alpha1_PackageManifestImage is an autogenerated conversion function.
func Convert_manifests_PackageManifestImage_To_v1alpha1_PackageManifestImage(in *PackageManifestImage, out *v1alpha1.PackageManifestImage, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestImage_To_v1alpha1_PackageManifestImage(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestImage_To_manifests_PackageManifestImage(in *v1alpha1.PackageManifestImage, out *PackageManifestImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_PackageManifestImage_To_manifests_PackageManifestImage is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestImage_To_manifests_PackageManifestImage(in *v1alpha1.PackageManifestImage, out *PackageManifestImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestImage_To_manifests_PackageManifestImage(in, out, s)
}

func autoConvert_manifests_PackageManifestLock_To_v1alpha1_PackageManifestLock(in *PackageManifestLock, out *v1alpha1.PackageManifestLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_manifests_PackageManifestLockSpec_To_v1alpha1_PackageManifestLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_manifests_PackageManifestLock_To_v1alpha1_PackageManifestLock is an autogenerated conversion function.
func Convert_manifests_PackageManifestLock_To_v1alpha1_PackageManifestLock(in *PackageManifestLock, out *v1alpha1.PackageManifestLock, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestLock_To_v1alpha1_PackageManifestLock(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestLock_To_manifests_PackageManifestLock(in *v1alpha1.PackageManifestLock, out *PackageManifestLock, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PackageManifestLockSpec_To_manifests_PackageManifestLockSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PackageManifestLock_To_manifests_PackageManifestLock is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestLock_To_manifests_PackageManifestLock(in *v1alpha1.PackageManifestLock, out *PackageManifestLock, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestLock_To_manifests_PackageManifestLock(in, out, s)
}

func autoConvert_manifests_PackageManifestLockDependency_To_v1alpha1_PackageManifestLockDependency(in *PackageManifestLockDependency, out *v1alpha1.PackageManifestLockDependency, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Digest = in.Digest
	out.Version = in.Version
	return nil
}

// Convert_manifests_PackageManifestLockDependency_To_v1alpha1_PackageManifestLockDependency is an autogenerated conversion function.
func Convert_manifests_PackageManifestLockDependency_To_v1alpha1_PackageManifestLockDependency(in *PackageManifestLockDependency, out *v1alpha1.PackageManifestLockDependency, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestLockDependency_To_v1alpha1_PackageManifestLockDependency(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestLockDependency_To_manifests_PackageManifestLockDependency(in *v1alpha1.PackageManifestLockDependency, out *PackageManifestLockDependency, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Digest = in.Digest
	out.Version = in.Version
	return nil
}

// Convert_v1alpha1_PackageManifestLockDependency_To_manifests_PackageManifestLockDependency is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestLockDependency_To_manifests_PackageManifestLockDependency(in *v1alpha1.PackageManifestLockDependency, out *PackageManifestLockDependency, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestLockDependency_To_manifests_PackageManifestLockDependency(in, out, s)
}

func autoConvert_manifests_PackageManifestLockImage_To_v1alpha1_PackageManifestLockImage(in *PackageManifestLockImage, out *v1alpha1.PackageManifestLockImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Digest = in.Digest
	return nil
}

// Convert_manifests_PackageManifestLockImage_To_v1alpha1_PackageManifestLockImage is an autogenerated conversion function.
func Convert_manifests_PackageManifestLockImage_To_v1alpha1_PackageManifestLockImage(in *PackageManifestLockImage, out *v1alpha1.PackageManifestLockImage, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestLockImage_To_v1alpha1_PackageManifestLockImage(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestLockImage_To_manifests_PackageManifestLockImage(in *v1alpha1.PackageManifestLockImage, out *PackageManifestLockImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Image = in.Image
	out.Digest = in.Digest
	return nil
}

// Convert_v1alpha1_PackageManifestLockImage_To_manifests_PackageManifestLockImage is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestLockImage_To_manifests_PackageManifestLockImage(in *v1alpha1.PackageManifestLockImage, out *PackageManifestLockImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestLockImage_To_manifests_PackageManifestLockImage(in, out, s)
}

func autoConvert_manifests_PackageManifestLockSpec_To_v1alpha1_PackageManifestLockSpec(in *PackageManifestLockSpec, out *v1alpha1.PackageManifestLockSpec, s conversion.Scope) error {
	out.Images = *(*[]v1alpha1.PackageManifestLockImage)(unsafe.Pointer(&in.Images))
	out.Dependencies = *(*[]v1alpha1.PackageManifestLockDependency)(unsafe.Pointer(&in.Dependencies))
	return nil
}

// Convert_manifests_PackageManifestLockSpec_To_v1alpha1_PackageManifestLockSpec is an autogenerated conversion function.
func Convert_manifests_PackageManifestLockSpec_To_v1alpha1_PackageManifestLockSpec(in *PackageManifestLockSpec, out *v1alpha1.PackageManifestLockSpec, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestLockSpec_To_v1alpha1_PackageManifestLockSpec(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestLockSpec_To_manifests_PackageManifestLockSpec(in *v1alpha1.PackageManifestLockSpec, out *PackageManifestLockSpec, s conversion.Scope) error {
	out.Images = *(*[]PackageManifestLockImage)(unsafe.Pointer(&in.Images))
	out.Dependencies = *(*[]PackageManifestLockDependency)(unsafe.Pointer(&in.Dependencies))
	return nil
}

// Convert_v1alpha1_PackageManifestLockSpec_To_manifests_PackageManifestLockSpec is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestLockSpec_To_manifests_PackageManifestLockSpec(in *v1alpha1.PackageManifestLockSpec, out *PackageManifestLockSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestLockSpec_To_manifests_PackageManifestLockSpec(in, out, s)
}

func autoConvert_manifests_PackageManifestPhase_To_v1alpha1_PackageManifestPhase(in *PackageManifestPhase, out *v1alpha1.PackageManifestPhase, s conversion.Scope) error {
	out.Name = in.Name
	out.Class = in.Class
	return nil
}

// Convert_manifests_PackageManifestPhase_To_v1alpha1_PackageManifestPhase is an autogenerated conversion function.
func Convert_manifests_PackageManifestPhase_To_v1alpha1_PackageManifestPhase(in *PackageManifestPhase, out *v1alpha1.PackageManifestPhase, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestPhase_To_v1alpha1_PackageManifestPhase(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestPhase_To_manifests_PackageManifestPhase(in *v1alpha1.PackageManifestPhase, out *PackageManifestPhase, s conversion.Scope) error {
	out.Name = in.Name
	out.Class = in.Class
	return nil
}

// Convert_v1alpha1_PackageManifestPhase_To_manifests_PackageManifestPhase is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestPhase_To_manifests_PackageManifestPhase(in *v1alpha1.PackageManifestPhase, out *PackageManifestPhase, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestPhase_To_manifests_PackageManifestPhase(in, out, s)
}

func autoConvert_manifests_PackageManifestPlatformVersionConstraint_To_v1alpha1_PackageManifestPlatformVersionConstraint(in *PackageManifestPlatformVersionConstraint, out *v1alpha1.PackageManifestPlatformVersionConstraint, s conversion.Scope) error {
	out.Name = v1alpha1.PlatformName(in.Name)
	out.Range = in.Range
	return nil
}

// Convert_manifests_PackageManifestPlatformVersionConstraint_To_v1alpha1_PackageManifestPlatformVersionConstraint is an autogenerated conversion function.
func Convert_manifests_PackageManifestPlatformVersionConstraint_To_v1alpha1_PackageManifestPlatformVersionConstraint(in *PackageManifestPlatformVersionConstraint, out *v1alpha1.PackageManifestPlatformVersionConstraint, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestPlatformVersionConstraint_To_v1alpha1_PackageManifestPlatformVersionConstraint(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestPlatformVersionConstraint_To_manifests_PackageManifestPlatformVersionConstraint(in *v1alpha1.PackageManifestPlatformVersionConstraint, out *PackageManifestPlatformVersionConstraint, s conversion.Scope) error {
	out.Name = PlatformName(in.Name)
	out.Range = in.Range
	return nil
}

// Convert_v1alpha1_PackageManifestPlatformVersionConstraint_To_manifests_PackageManifestPlatformVersionConstraint is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestPlatformVersionConstraint_To_manifests_PackageManifestPlatformVersionConstraint(in *v1alpha1.PackageManifestPlatformVersionConstraint, out *PackageManifestPlatformVersionConstraint, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestPlatformVersionConstraint_To_manifests_PackageManifestPlatformVersionConstraint(in, out, s)
}

func autoConvert_manifests_PackageManifestRepository_To_v1alpha1_PackageManifestRepository(in *PackageManifestRepository, out *v1alpha1.PackageManifestRepository, s conversion.Scope) error {
	out.File = in.File
	out.Image = in.Image
	return nil
}

// Convert_manifests_PackageManifestRepository_To_v1alpha1_PackageManifestRepository is an autogenerated conversion function.
func Convert_manifests_PackageManifestRepository_To_v1alpha1_PackageManifestRepository(in *PackageManifestRepository, out *v1alpha1.PackageManifestRepository, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestRepository_To_v1alpha1_PackageManifestRepository(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestRepository_To_manifests_PackageManifestRepository(in *v1alpha1.PackageManifestRepository, out *PackageManifestRepository, s conversion.Scope) error {
	out.File = in.File
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_PackageManifestRepository_To_manifests_PackageManifestRepository is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestRepository_To_manifests_PackageManifestRepository(in *v1alpha1.PackageManifestRepository, out *PackageManifestRepository, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestRepository_To_manifests_PackageManifestRepository(in, out, s)
}

func autoConvert_manifests_PackageManifestSpec_To_v1alpha1_PackageManifestSpec(in *PackageManifestSpec, out *v1alpha1.PackageManifestSpec, s conversion.Scope) error {
	out.Scopes = *(*[]v1alpha1.PackageManifestScope)(unsafe.Pointer(&in.Scopes))
	out.Phases = *(*[]v1alpha1.PackageManifestPhase)(unsafe.Pointer(&in.Phases))
	out.AvailabilityProbes = *(*[]corev1alpha1.ObjectSetProbe)(unsafe.Pointer(&in.AvailabilityProbes))
	if err := Convert_manifests_PackageManifestSpecConfig_To_v1alpha1_PackageManifestSpecConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.Images = *(*[]v1alpha1.PackageManifestImage)(unsafe.Pointer(&in.Images))
	out.Components = (*v1alpha1.PackageManifestComponentsConfig)(unsafe.Pointer(in.Components))
	out.Constraints = *(*[]v1alpha1.PackageManifestConstraint)(unsafe.Pointer(&in.Constraints))
	out.Repositories = *(*[]v1alpha1.PackageManifestRepository)(unsafe.Pointer(&in.Repositories))
	out.Dependencies = *(*[]v1alpha1.PackageManifestDependency)(unsafe.Pointer(&in.Dependencies))
	return nil
}

// Convert_manifests_PackageManifestSpec_To_v1alpha1_PackageManifestSpec is an autogenerated conversion function.
func Convert_manifests_PackageManifestSpec_To_v1alpha1_PackageManifestSpec(in *PackageManifestSpec, out *v1alpha1.PackageManifestSpec, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestSpec_To_v1alpha1_PackageManifestSpec(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestSpec_To_manifests_PackageManifestSpec(in *v1alpha1.PackageManifestSpec, out *PackageManifestSpec, s conversion.Scope) error {
	out.Scopes = *(*[]PackageManifestScope)(unsafe.Pointer(&in.Scopes))
	out.Phases = *(*[]PackageManifestPhase)(unsafe.Pointer(&in.Phases))
	out.AvailabilityProbes = *(*[]corev1alpha1.ObjectSetProbe)(unsafe.Pointer(&in.AvailabilityProbes))
	if err := Convert_v1alpha1_PackageManifestSpecConfig_To_manifests_PackageManifestSpecConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	out.Images = *(*[]PackageManifestImage)(unsafe.Pointer(&in.Images))
	out.Components = (*PackageManifestComponentsConfig)(unsafe.Pointer(in.Components))
	out.Constraints = *(*[]PackageManifestConstraint)(unsafe.Pointer(&in.Constraints))
	out.Repositories = *(*[]PackageManifestRepository)(unsafe.Pointer(&in.Repositories))
	out.Dependencies = *(*[]PackageManifestDependency)(unsafe.Pointer(&in.Dependencies))
	return nil
}

// Convert_v1alpha1_PackageManifestSpec_To_manifests_PackageManifestSpec is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestSpec_To_manifests_PackageManifestSpec(in *v1alpha1.PackageManifestSpec, out *PackageManifestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestSpec_To_manifests_PackageManifestSpec(in, out, s)
}

func autoConvert_manifests_PackageManifestSpecConfig_To_v1alpha1_PackageManifestSpecConfig(in *PackageManifestSpecConfig, out *v1alpha1.PackageManifestSpecConfig, s conversion.Scope) error {
	if in.OpenAPIV3Schema != nil {
		in, out := &in.OpenAPIV3Schema, &out.OpenAPIV3Schema
		*out = new(v1.JSONSchemaProps)
		if err := v1.Convert_apiextensions_JSONSchemaProps_To_v1_JSONSchemaProps(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OpenAPIV3Schema = nil
	}
	return nil
}

// Convert_manifests_PackageManifestSpecConfig_To_v1alpha1_PackageManifestSpecConfig is an autogenerated conversion function.
func Convert_manifests_PackageManifestSpecConfig_To_v1alpha1_PackageManifestSpecConfig(in *PackageManifestSpecConfig, out *v1alpha1.PackageManifestSpecConfig, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestSpecConfig_To_v1alpha1_PackageManifestSpecConfig(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestSpecConfig_To_manifests_PackageManifestSpecConfig(in *v1alpha1.PackageManifestSpecConfig, out *PackageManifestSpecConfig, s conversion.Scope) error {
	if in.OpenAPIV3Schema != nil {
		in, out := &in.OpenAPIV3Schema, &out.OpenAPIV3Schema
		*out = new(apiextensions.JSONSchemaProps)
		if err := Convert_v1_JSONSchemaProps_To_apiextensions_JSONSchemaProps(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.OpenAPIV3Schema = nil
	}
	return nil
}

// Convert_v1alpha1_PackageManifestSpecConfig_To_manifests_PackageManifestSpecConfig is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestSpecConfig_To_manifests_PackageManifestSpecConfig(in *v1alpha1.PackageManifestSpecConfig, out *PackageManifestSpecConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestSpecConfig_To_manifests_PackageManifestSpecConfig(in, out, s)
}

func autoConvert_manifests_PackageManifestTest_To_v1alpha1_PackageManifestTest(in *PackageManifestTest, out *v1alpha1.PackageManifestTest, s conversion.Scope) error {
	out.Template = *(*[]v1alpha1.PackageManifestTestCaseTemplate)(unsafe.Pointer(&in.Template))
	out.Kubeconform = (*v1alpha1.PackageManifestTestKubeconform)(unsafe.Pointer(in.Kubeconform))
	return nil
}

// Convert_manifests_PackageManifestTest_To_v1alpha1_PackageManifestTest is an autogenerated conversion function.
func Convert_manifests_PackageManifestTest_To_v1alpha1_PackageManifestTest(in *PackageManifestTest, out *v1alpha1.PackageManifestTest, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestTest_To_v1alpha1_PackageManifestTest(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestTest_To_manifests_PackageManifestTest(in *v1alpha1.PackageManifestTest, out *PackageManifestTest, s conversion.Scope) error {
	out.Template = *(*[]PackageManifestTestCaseTemplate)(unsafe.Pointer(&in.Template))
	out.Kubeconform = (*PackageManifestTestKubeconform)(unsafe.Pointer(in.Kubeconform))
	return nil
}

// Convert_v1alpha1_PackageManifestTest_To_manifests_PackageManifestTest is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestTest_To_manifests_PackageManifestTest(in *v1alpha1.PackageManifestTest, out *PackageManifestTest, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestTest_To_manifests_PackageManifestTest(in, out, s)
}

func autoConvert_manifests_PackageManifestTestCaseTemplate_To_v1alpha1_PackageManifestTestCaseTemplate(in *PackageManifestTestCaseTemplate, out *v1alpha1.PackageManifestTestCaseTemplate, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_manifests_TemplateContext_To_v1alpha1_TemplateContext(&in.Context, &out.Context, s); err != nil {
		return err
	}
	return nil
}

// Convert_manifests_PackageManifestTestCaseTemplate_To_v1alpha1_PackageManifestTestCaseTemplate is an autogenerated conversion function.
func Convert_manifests_PackageManifestTestCaseTemplate_To_v1alpha1_PackageManifestTestCaseTemplate(in *PackageManifestTestCaseTemplate, out *v1alpha1.PackageManifestTestCaseTemplate, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestTestCaseTemplate_To_v1alpha1_PackageManifestTestCaseTemplate(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestTestCaseTemplate_To_manifests_PackageManifestTestCaseTemplate(in *v1alpha1.PackageManifestTestCaseTemplate, out *PackageManifestTestCaseTemplate, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_TemplateContext_To_manifests_TemplateContext(&in.Context, &out.Context, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_PackageManifestTestCaseTemplate_To_manifests_PackageManifestTestCaseTemplate is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestTestCaseTemplate_To_manifests_PackageManifestTestCaseTemplate(in *v1alpha1.PackageManifestTestCaseTemplate, out *PackageManifestTestCaseTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestTestCaseTemplate_To_manifests_PackageManifestTestCaseTemplate(in, out, s)
}

func autoConvert_manifests_PackageManifestTestKubeconform_To_v1alpha1_PackageManifestTestKubeconform(in *PackageManifestTestKubeconform, out *v1alpha1.PackageManifestTestKubeconform, s conversion.Scope) error {
	out.KubernetesVersion = in.KubernetesVersion
	out.SchemaLocations = *(*[]string)(unsafe.Pointer(&in.SchemaLocations))
	return nil
}

// Convert_manifests_PackageManifestTestKubeconform_To_v1alpha1_PackageManifestTestKubeconform is an autogenerated conversion function.
func Convert_manifests_PackageManifestTestKubeconform_To_v1alpha1_PackageManifestTestKubeconform(in *PackageManifestTestKubeconform, out *v1alpha1.PackageManifestTestKubeconform, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestTestKubeconform_To_v1alpha1_PackageManifestTestKubeconform(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestTestKubeconform_To_manifests_PackageManifestTestKubeconform(in *v1alpha1.PackageManifestTestKubeconform, out *PackageManifestTestKubeconform, s conversion.Scope) error {
	out.KubernetesVersion = in.KubernetesVersion
	out.SchemaLocations = *(*[]string)(unsafe.Pointer(&in.SchemaLocations))
	return nil
}

// Convert_v1alpha1_PackageManifestTestKubeconform_To_manifests_PackageManifestTestKubeconform is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestTestKubeconform_To_manifests_PackageManifestTestKubeconform(in *v1alpha1.PackageManifestTestKubeconform, out *PackageManifestTestKubeconform, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestTestKubeconform_To_manifests_PackageManifestTestKubeconform(in, out, s)
}

func autoConvert_manifests_PackageManifestUniqueInScopeConstraint_To_v1alpha1_PackageManifestUniqueInScopeConstraint(in *PackageManifestUniqueInScopeConstraint, out *v1alpha1.PackageManifestUniqueInScopeConstraint, s conversion.Scope) error {
	return nil
}

// Convert_manifests_PackageManifestUniqueInScopeConstraint_To_v1alpha1_PackageManifestUniqueInScopeConstraint is an autogenerated conversion function.
func Convert_manifests_PackageManifestUniqueInScopeConstraint_To_v1alpha1_PackageManifestUniqueInScopeConstraint(in *PackageManifestUniqueInScopeConstraint, out *v1alpha1.PackageManifestUniqueInScopeConstraint, s conversion.Scope) error {
	return autoConvert_manifests_PackageManifestUniqueInScopeConstraint_To_v1alpha1_PackageManifestUniqueInScopeConstraint(in, out, s)
}

func autoConvert_v1alpha1_PackageManifestUniqueInScopeConstraint_To_manifests_PackageManifestUniqueInScopeConstraint(in *v1alpha1.PackageManifestUniqueInScopeConstraint, out *PackageManifestUniqueInScopeConstraint, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_PackageManifestUniqueInScopeConstraint_To_manifests_PackageManifestUniqueInScopeConstraint is an autogenerated conversion function.
func Convert_v1alpha1_PackageManifestUniqueInScopeConstraint_To_manifests_PackageManifestUniqueInScopeConstraint(in *v1alpha1.PackageManifestUniqueInScopeConstraint, out *PackageManifestUniqueInScopeConstraint, s conversion.Scope) error {
	return autoConvert_v1alpha1_PackageManifestUniqueInScopeConstraint_To_manifests_PackageManifestUniqueInScopeConstraint(in, out, s)
}

func autoConvert_manifests_Repository_To_v1alpha1_Repository(in *Repository, out *v1alpha1.Repository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_manifests_Repository_To_v1alpha1_Repository is an autogenerated conversion function.
func Convert_manifests_Repository_To_v1alpha1_Repository(in *Repository, out *v1alpha1.Repository, s conversion.Scope) error {
	return autoConvert_manifests_Repository_To_v1alpha1_Repository(in, out, s)
}

func autoConvert_v1alpha1_Repository_To_manifests_Repository(in *v1alpha1.Repository, out *Repository, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	return nil
}

// Convert_v1alpha1_Repository_To_manifests_Repository is an autogenerated conversion function.
func Convert_v1alpha1_Repository_To_manifests_Repository(in *v1alpha1.Repository, out *Repository, s conversion.Scope) error {
	return autoConvert_v1alpha1_Repository_To_manifests_Repository(in, out, s)
}

func autoConvert_manifests_RepositoryEntry_To_v1alpha1_RepositoryEntry(in *RepositoryEntry, out *v1alpha1.RepositoryEntry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_manifests_RepositoryEntryData_To_v1alpha1_RepositoryEntryData(&in.Data, &out.Data, s); err != nil {
		return err
	}
	return nil
}

// Convert_manifests_RepositoryEntry_To_v1alpha1_RepositoryEntry is an autogenerated conversion function.
func Convert_manifests_RepositoryEntry_To_v1alpha1_RepositoryEntry(in *RepositoryEntry, out *v1alpha1.RepositoryEntry, s conversion.Scope) error {
	return autoConvert_manifests_RepositoryEntry_To_v1alpha1_RepositoryEntry(in, out, s)
}

func autoConvert_v1alpha1_RepositoryEntry_To_manifests_RepositoryEntry(in *v1alpha1.RepositoryEntry, out *RepositoryEntry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RepositoryEntryData_To_manifests_RepositoryEntryData(&in.Data, &out.Data, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RepositoryEntry_To_manifests_RepositoryEntry is an autogenerated conversion function.
func Convert_v1alpha1_RepositoryEntry_To_manifests_RepositoryEntry(in *v1alpha1.RepositoryEntry, out *RepositoryEntry, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepositoryEntry_To_manifests_RepositoryEntry(in, out, s)
}

func autoConvert_manifests_RepositoryEntryData_To_v1alpha1_RepositoryEntryData(in *RepositoryEntryData, out *v1alpha1.RepositoryEntryData, s conversion.Scope) error {
	out.Image = in.Image
	out.Digest = in.Digest
	out.Versions = *(*[]string)(unsafe.Pointer(&in.Versions))
	out.Constraints = *(*[]v1alpha1.PackageManifestConstraint)(unsafe.Pointer(&in.Constraints))
	out.Name = in.Name
	return nil
}

// Convert_manifests_RepositoryEntryData_To_v1alpha1_RepositoryEntryData is an autogenerated conversion function.
func Convert_manifests_RepositoryEntryData_To_v1alpha1_RepositoryEntryData(in *RepositoryEntryData, out *v1alpha1.RepositoryEntryData, s conversion.Scope) error {
	return autoConvert_manifests_RepositoryEntryData_To_v1alpha1_RepositoryEntryData(in, out, s)
}

func autoConvert_v1alpha1_RepositoryEntryData_To_manifests_RepositoryEntryData(in *v1alpha1.RepositoryEntryData, out *RepositoryEntryData, s conversion.Scope) error {
	out.Image = in.Image
	out.Digest = in.Digest
	out.Versions = *(*[]string)(unsafe.Pointer(&in.Versions))
	out.Constraints = *(*[]PackageManifestConstraint)(unsafe.Pointer(&in.Constraints))
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_RepositoryEntryData_To_manifests_RepositoryEntryData is an autogenerated conversion function.
func Convert_v1alpha1_RepositoryEntryData_To_manifests_RepositoryEntryData(in *v1alpha1.RepositoryEntryData, out *RepositoryEntryData, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepositoryEntryData_To_manifests_RepositoryEntryData(in, out, s)
}

func autoConvert_manifests_TemplateContext_To_v1alpha1_TemplateContext(in *TemplateContext, out *v1alpha1.TemplateContext, s conversion.Scope) error {
	if err := Convert_manifests_TemplateContextPackage_To_v1alpha1_TemplateContextPackage(&in.Package, &out.Package, s); err != nil {
		return err
	}
	out.Config = (*runtime.RawExtension)(unsafe.Pointer(in.Config))
	if err := Convert_manifests_PackageEnvironment_To_v1alpha1_PackageEnvironment(&in.Environment, &out.Environment, s); err != nil {
		return err
	}
	return nil
}

// Convert_manifests_TemplateContext_To_v1alpha1_TemplateContext is an autogenerated conversion function.
func Convert_manifests_TemplateContext_To_v1alpha1_TemplateContext(in *TemplateContext, out *v1alpha1.TemplateContext, s conversion.Scope) error {
	return autoConvert_manifests_TemplateContext_To_v1alpha1_TemplateContext(in, out, s)
}

func autoConvert_v1alpha1_TemplateContext_To_manifests_TemplateContext(in *v1alpha1.TemplateContext, out *TemplateContext, s conversion.Scope) error {
	if err := Convert_v1alpha1_TemplateContextPackage_To_manifests_TemplateContextPackage(&in.Package, &out.Package, s); err != nil {
		return err
	}
	out.Config = (*runtime.RawExtension)(unsafe.Pointer(in.Config))
	if err := Convert_v1alpha1_PackageEnvironment_To_manifests_PackageEnvironment(&in.Environment, &out.Environment, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TemplateContext_To_manifests_TemplateContext is an autogenerated conversion function.
func Convert_v1alpha1_TemplateContext_To_manifests_TemplateContext(in *v1alpha1.TemplateContext, out *TemplateContext, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateContext_To_manifests_TemplateContext(in, out, s)
}

func autoConvert_manifests_TemplateContextObjectMeta_To_v1alpha1_TemplateContextObjectMeta(in *TemplateContextObjectMeta, out *v1alpha1.TemplateContextObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_manifests_TemplateContextObjectMeta_To_v1alpha1_TemplateContextObjectMeta is an autogenerated conversion function.
func Convert_manifests_TemplateContextObjectMeta_To_v1alpha1_TemplateContextObjectMeta(in *TemplateContextObjectMeta, out *v1alpha1.TemplateContextObjectMeta, s conversion.Scope) error {
	return autoConvert_manifests_TemplateContextObjectMeta_To_v1alpha1_TemplateContextObjectMeta(in, out, s)
}

func autoConvert_v1alpha1_TemplateContextObjectMeta_To_manifests_TemplateContextObjectMeta(in *v1alpha1.TemplateContextObjectMeta, out *TemplateContextObjectMeta, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	return nil
}

// Convert_v1alpha1_TemplateContextObjectMeta_To_manifests_TemplateContextObjectMeta is an autogenerated conversion function.
func Convert_v1alpha1_TemplateContextObjectMeta_To_manifests_TemplateContextObjectMeta(in *v1alpha1.TemplateContextObjectMeta, out *TemplateContextObjectMeta, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateContextObjectMeta_To_manifests_TemplateContextObjectMeta(in, out, s)
}

func autoConvert_manifests_TemplateContextPackage_To_v1alpha1_TemplateContextPackage(in *TemplateContextPackage, out *v1alpha1.TemplateContextPackage, s conversion.Scope) error {
	if err := Convert_manifests_TemplateContextObjectMeta_To_v1alpha1_TemplateContextObjectMeta(&in.TemplateContextObjectMeta, &out.TemplateContextObjectMeta, s); err != nil {
		return err
	}
	return nil
}

// Convert_manifests_TemplateContextPackage_To_v1alpha1_TemplateContextPackage is an autogenerated conversion function.
func Convert_manifests_TemplateContextPackage_To_v1alpha1_TemplateContextPackage(in *TemplateContextPackage, out *v1alpha1.TemplateContextPackage, s conversion.Scope) error {
	return autoConvert_manifests_TemplateContextPackage_To_v1alpha1_TemplateContextPackage(in, out, s)
}

func autoConvert_v1alpha1_TemplateContextPackage_To_manifests_TemplateContextPackage(in *v1alpha1.TemplateContextPackage, out *TemplateContextPackage, s conversion.Scope) error {
	if err := Convert_v1alpha1_TemplateContextObjectMeta_To_manifests_TemplateContextObjectMeta(&in.TemplateContextObjectMeta, &out.TemplateContextObjectMeta, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TemplateContextPackage_To_manifests_TemplateContextPackage is an autogenerated conversion function.
func Convert_v1alpha1_TemplateContextPackage_To_manifests_TemplateContextPackage(in *v1alpha1.TemplateContextPackage, out *TemplateContextPackage, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateContextPackage_To_manifests_TemplateContextPackage(in, out, s)
}
