apiVersion: package-operator.run/v1alpha1
kind: SecretSync
metadata:
  name: defaulting
spec:
  src:
    namespace: kube-system
    name: bootstrap-token-abcdef
  dest:
  - namespace: default
    name: default-bootstrap-token
