apiVersion: v1
kind: ConfigMap
metadata:
  name: "test-cm"
  labels:
    app: test-stub
    instance: "test"
  annotations:
    test-environment: "{\"kubernetes\":{\"version\":\"v1.27.0\"}}"
    package-operator.run/phase: deploy
    package-operator.run/condition: "false"
data:
  banana: "bread"
