apiVersion: v1
kind: ConfigMap
metadata:
  name: "ignored-cm"
  labels:
    app: test-stub
    instance: "test"
  annotations:
    test-environment: "{\"kubernetes\":{\"version\":\"v1.27.0\"}}"
    package-operator.run/phase: deploy
data:
  banana: "bread"
